hexops/mach

.github/workflows/ci.yml
glfw/build.zig

CI: add pipeline for Windows; Windows->MacOS cross compilation

---

glfw/build.zig

This change makes it easier to test SDKs locally, e.g. if you have:
```
% tree projects/
projects
├── mach
│   └── glfw
└── sdk-macos-11.3
```
In the `projects/mach/glfw` directory it is now easy to test changes to `sdk-macos-11.3` using:
```sh
SDK_PATH="$(pwd)/../.." zig build test -Dtarget=aarch64-macos
```
And it'll use your local SDK, instead of the one in the appdata dir.

glfw: add SDK_PATH for easier testing of changes to SDKs

---

.github/workflows/ci.yml
.github/workflows/m1_ci.yml
README.md

CI: add aarch64-macos / M1 self-hosted runner

---

.github/workflows/ci.yml
README.md

verify cross compilation: x86_64-macos -> aarch64-macos

---

.github/workflows/ci.yml

CI: cleanup naming conventions

---

.github/workflows/ci.yml
README.md

CI: add linux/windows -> aarch64-macos tests

---

.github/workflows/ci.yml

CI: update to latest nightly Zig b87105c92

---

.github/workflows/ci.yml
README.md
glfw/build.zig

Windows support

---

.github/workflows/ci.yml
.github/workflows/m1_ci.yml
README.md

Windows cross compilation support

---

glfw/build.zig

Hey! I ran into linking issues when incorporating this into a project because the engine lib was picking up my own `src/main.zig`, I don't think this intermediate static lib is actually needed (at least on linux) so adding source directly to the step should do. (fingers crossed on that CI)

remove intermediate static lib

---

.github/workflows/ci.yml
glfw/build.zig

Update to latest Zig nightly

---

glfw/src/vulkan.zig

Having `glfw.getInstanceProcAddress` conform to the GLFW C ABI is important as it is often
likely to be passed into libraries which expect exactly that ABI, e.g. zig-vulkan.
Fixes hexops/mach#49

glfw: make glfw.getInstanceProcAddress conform to GLFW C ABI

---

glfw/README.md

glfw: polish README, add getting started, error handling, etc. sections

---

glfw/README.md

glfw: correct error handling in README example

---

glfw/build.zig

Fixes https://github.com/hexops/mach/issues/76

glfw: fix typo prevents building for Wayland

---

glfw/src/Window.zig

Tests pass on my machine right now, but also unsure whether this is as comprehensive as it could be, hence the mess of comments. Any feedback or insights would be greatly appreciated.

glfw: window hint default values parity test with attributes

---

.github/workflows/ci.yml
glfw/.github/workflows/ci.yml
glfw/system_sdk.zig

glfw: fix support for macOS 11 cross compilation

---

gpu/build_dawn.zig
gpu/src/dawn/dawn_native_mach.cpp
gpu/src/dawn/dawn_native_mach.h

Brings us two months worth of goodies. See https://github.com/hexops/dawn/pull/1

gpu: update to latest Dawn version

---

.github/workflows/ci.yml
glfw/.github/workflows/ci.yml
glfw/src/GammaRamp.zig
glfw/src/Image.zig
glfw/src/Monitor.zig
glfw/src/Window.zig
glfw/system_sdk.zig
gpu/src/dawn/hello_triangle.zig

supersedes hexops/mach#116 (adds additional commits)

update to latest Zig master

---

glfw/src/Window.zig
glfw/src/main.zig

glfw: remove invalid TODOs

---

glfw/system_sdk.zig

This substantially reduces consecutive build times when using mach/glfw.
`system_sdk.getSdkPath` is frequently invoked as part of the build process, and previously it was doing some fairly involved work (ensuring the native SDK is at the right revision, needless `git fetch` in native SDKs to check for updates, etc.)
We now do far less work in `getSdkPath`, and additionally cache the result in-memory. This improves build times substantially, but especially so with consecutive (non-cold-cache) build times:
* For `mach/glfw`: ~2s before, ~160ms after
* For `mach/gpu`: , ~16s before, ~3.6s after

glfw: improve consecutive build times by 4-12x

---

glfw/src/Cursor.zig
glfw/src/GammaRamp.zig
glfw/src/Image.zig
glfw/src/Joystick.zig
glfw/src/Monitor.zig
glfw/src/VideoMode.zig
glfw/src/Window.zig
glfw/src/key.zig
glfw/src/opengl.zig

replaced isize, usize with i32, u32

---

.github/workflows/ci.yml
glfw/.github/workflows/ci.yml
glfw/src/Joystick.zig
glfw/src/Window.zig

Zig master changed `c_void` to `anyopaque`, and zig fmt helps to change code as appropriate.

Run zig fmt + Update CI

---

glfw/update-upstream.sh

glfw: update `update-upstream.sh` to clone faster

---

glfw/src/main.zig
glfw/src/native.zig

glfw: add ziggified API of glfw3native.h

---

glfw/src/Monitor.zig
glfw/src/vulkan.zig

glfw: Update function docs in Monitor and vulkan to match glfw 3.3.6

---

.gitmodules

I noticed building of dawn was broken as a result of #139 . This small PR fixes it
Builds locally for me

gpu-dawn: Fix building after the rename of gpu -> gpu-dawn

---

glfw/src/native.zig

- Added hidden error returns
- Improved return types
- Updated docs to glfw 3.3.6
Fixes: https://github.com/hexops/mach/pull/134#issuecomment-999784230

glfw: improve documentation for native.zig

---

glfw/upstream/glfw/src/x11_window.c

fixes issue until [#1989](https://github.com/glfw/glfw/pull/1989) is merged. related to #149

glfw: repatch undefined behaviour in X11 keypress handling

---

glfw/src/errors.zig

This PR changes `setErrorCallback` to take a callback with nice zig types.
As this callback can be set before `glfwInit` is called the method of storing function pointers on `InternalUserPointer` cannot be used.
To make it work the function provided by the user must be comptime known allowing us to construct a c wrapper function inline.

glfw: improve `setErrorCallback`

---

glfw/README.md

glfw: add instructions for Gyro in README.md

---

gpu/examples/sample_utils.zig

This PR fixes the an issue with the samples on Windows using the latest version of Zig.

gpu: update GetModuleHandleW usage in examples

---

glfw/system_sdk.zig

system_sdk for linux-aarch64

---

ecs/README.md

https://devlog.hexops.com/categories/build-an-ecs/

---

gpu/src/Texture.zig
gpu/src/data.zig
gpu/src/structs.zig

This makes the code much less verbose.

gpu: Add default values for some structs (taken from the spec).

---

gpu/src/Sampler.zig

fix sampler typo

---

build.zig
gpu/build.zig

do not produce needless libraries

---

gpu/src/Adapter.zig
gpu/src/Buffer.zig
gpu/src/ComputePipeline.zig
gpu/src/Device.zig
gpu/src/Interface.zig
gpu/src/NativeInstance.zig
gpu/src/Queue.zig
gpu/src/RenderPipeline.zig
gpu/src/ShaderModule.zig
gpu/src/structs.zig

Fixed ErrorCallback.init() alignment

---

gpu-dawn/build.zig

gpu-dawn: fix compilation on Linux

---

examples/rotating-cube/main.zig
examples/two-cubes/main.zig

Fixed BlendState for rotating-cube and two-cubes

---

build.zig
shaderexp/README.md
shaderexp/black_screen_frag.wgsl
shaderexp/example-shaders/mandelbrot.wgsl
shaderexp/example-shaders/ray_marching.wgsl
shaderexp/example-shaders/test_shader.wgsl
shaderexp/frag.wgsl
shaderexp/main.zig
shaderexp/vert.wgsl

shaderexp: add initial shader explorer tool

---

gpu/src/Sampler.zig
gpu/src/Texture.zig
gpu/src/TextureView.zig

gpu: mirror more WebGPU spec default values

---

examples/fractal-cube/main.zig

Some resources were being freed twice, maybe because of copy-paste errors?

examples: fix incorrect release of resources in fractal-cube

---

.github/workflows/ci.yml
.gitmodules
build.zig
examples/boids/main.zig
glfw/.github/workflows/ci.yml
glfw/system_sdk.zig
gpu-dawn/.github/workflows/ci.yml
gpu-dawn/build.zig

- `std.math.ceil` has been removed https://github.com/ziglang/zig/commit/41dd2beaacade94c5c98400a4a655aea07b9e2f3
- `std.ChildProcess.init` does not allocate anymore https://github.com/ziglang/zig/commit/a0a2ce92ca129d28e22c63f7bace1672c43776b5

Update to Zig master

---

examples/fractal-cube/main.zig

Caused by https://github.com/hexops/mach/pull/258 (examples port)
---

examples: fix unwanted fractal cube resource releases causing validation error

---

examples/advanced-gen-texture-light/cube.wgsl

examples: fix typo

---

examples/instanced-cube/main.zig

examples: fixed uniform buffer release and unused var

---

build.zig
examples/gkurve/frag.wgsl
examples/gkurve/main.zig
examples/gkurve/vert.wgsl

There is still much missing, like textures, correct matrices for positioning and some form of dynamic arrays in wgsl, but it's a start

examples: created gkurve example

---

examples/advanced-gen-texture-light/main.zig
examples/fractal-cube/main.zig
examples/gkurve/main.zig
examples/instanced-cube/main.zig
examples/rotating-cube/main.zig
examples/textured-cube/main.zig
examples/two-cubes/main.zig
src/Engine.zig
src/main.zig
src/native.zig
src/structs.zig

Implemented the rest of raw glfw functions which were still in use. The added methods follow the same glfw naming, but can be changed later if desired.
Updated the examples with related to same.
---

mach: Create binding methods for all glfw methods in use and update examples

---

examples/gkurve/frag.wgsl
examples/gkurve/main.zig
examples/gkurve/vert.wgsl

examples/gkurve: simplify fragment shader, use barycentric coordinates

---

examples/gkurve/frag.wgsl
examples/gkurve/main.zig
examples/gkurve/vert.wgsl

examples/gkurve: use equadistant triangles, pixel units, cleanup code formatting

---

examples/gkurve/frag.wgsl
examples/gkurve/main.zig
examples/gkurve/vert.wgsl

examples: moved vertex uniform data to vertex buffer and added view

---

examples/advanced-gen-texture-light/main.zig
examples/fractal-cube/main.zig
examples/textured-cube/main.zig

This should fix an issue that resizing may sometime crash the program. It also releases the textures before recreating them

examples: fix depth texture recreation

---

gpu/src/Queue.zig

gpu: Fix build in 32-bit platforms

---

build.zig
examples/gkurve/draw.zig
examples/gkurve/frag.wgsl
examples/gkurve/main.zig

examples/gkurve: added shapes and textures

---

examples/gkurve/LICENSE.atlas
examples/gkurve/atlas.zig
examples/gkurve/draw.zig
examples/gkurve/frag.wgsl
examples/gkurve/main.zig

examples/gkurve: added texture atlas

---

src/Engine.zig
src/Timer.zig
src/mach.js
src/native.zig
src/platform.zig
src/wasm.zig

Implements:
- Inlining of Timer wrapper functions: https://github.com/hexops/mach/pull/279#discussion_r875531856
- Timer for wasm
- Standard way to access platform specific types: https://matrix.to/#/!hPlvgnLQhMkTucKPrh:matrix.org/$P8z6MgNuiwoirNlQS5LJBdddtl_lR2dfKn_aXRJY_ek?via=matrix.org
---

mach: Timer improvements

---

freetype/build.zig

freetype: improvments, more binding coverage, glyph_to_svg example

---

freetype/build.zig
freetype/examples/glyph_to_svg.zig
freetype/src/Glyph.zig
freetype/src/GlyphSlot.zig
freetype/src/Outline.zig
freetype/src/c.zig
freetype/src/types.zig

Freetype: add example builder/runner to build and implement some functions binding 

---

www/template.html

www: use console.error for logging wasm loader error

---

examples/advanced-gen-texture-light/main.zig
examples/gkurve/main.zig
examples/textured-cube/main.zig
gpu/src/Queue.zig

gpu: throw error if texture data is not slice

---

.github/workflows/ci.yml
.github/workflows/m1_ci.yml

CI: add freetype & update m1 ci name

---

freetype/build.zig
freetype/examples/glyph_to_svg.zig
freetype/src/Glyph.zig
freetype/src/GlyphSlot.zig
freetype/src/Outline.zig
freetype/src/c.zig
freetype/src/types.zig

@slimsag seems like you removed previous PR commits when force pushing. so i'd created it again but this time the glyph_to_svg example works
Closes #295

freetype: more binding coverage and examples

---

freetype/README.md

freetype: add running examples instruction

---

src/enums.zig
src/mach.js
src/structs.zig
src/wasm.zig

Apart from general improvements, it implements:
- https://github.com/hexops/mach/pull/286#discussion_r878909929
- Key events
Simple program I prepared for testing: https://gist.github.com/iddev5/ddbd9290e0a55b27fd0af5cbefb65aff
The process to run is the same as mentioned in #286 except that add the example to build.zig first. The proper build system run support will come in a different PR.
---

wasm: implement more functionality

---

build.zig

fixes to allow using mach as a library in standalone projects

mach: fix build.zig

---

build.zig
examples/gkurve/main.zig
examples/textured-cube/main.zig

Discussions:
- https://matrix.to/#/!hPlvgnLQhMkTucKPrh:matrix.org/$prOB0lkENIwtcQ14njWeyWRHAh6G6SZDY3EASBJAYFQ?via=matrix.org
- https://matrix.to/#/!hPlvgnLQhMkTucKPrh:matrix.org/$70yQCaJkN_ZBN0VUKdJKauX3Bfo7yCcTx7fT2muCUoI?via=matrix.org

examples: Load all images from Memory (using embedFile) instead of File

---

freetype/examples/glyph-to-svg.zig
freetype/src/Bitmap.zig
freetype/src/BitmapGlyph.zig
freetype/src/Face.zig
freetype/src/Glyph.zig
freetype/src/GlyphSlot.zig
freetype/src/Library.zig
freetype/src/Outline.zig
freetype/src/Stroker.zig
freetype/src/error.zig
freetype/src/types.zig

freetype: ziggify C structs and more

---

build.zig
examples/gkurve/main.zig
examples/gkurve/text.zig

examples/gkurve: added atlas text rendering and freetype linking

---

freetype/README.md

freetype: update example runner usage

---

build.zig
freetype/build.zig
glfw/build.zig
gpu/build.zig

Fix breaking change in Zig master, see https://github.com/ziglang/zig/pull/11557

Change std.build.Pkg.path to std.build.Pkg.source

---

build.zig
glfw/system_sdk.zig

glfw: ensure git present

---

src/platform/native.zig

Previously if user code called core.getWindowSize() (or
getFramebufferSize) during their update they could get sizes that did
not match engine.gpu_driver.target_desc because the window had changed
size.
Now core.getWindowSize() returns the last size we got from a glfw
callback instead of directly querying the window.  So all sizes should
agree during a single frame.
This relies on glfw callbacks only happening when we call
glfw.pollEvents().  This isn't strictly true - a callback could happen
during any glfw call.  Might have to revisit this later.

mach: save window and framebuffer size from glfw callbacks

---

examples/advanced-gen-texture-light/main.zig
examples/boids/main.zig
examples/fractal-cube/main.zig
examples/gkurve/main.zig
examples/instanced-cube/main.zig
examples/rotating-cube/main.zig
examples/textured-cube/main.zig
examples/triangle/main.zig
examples/two-cubes/main.zig
shaderexp/main.zig
src/Engine.zig
src/platform.zig
src/platform/native.zig
src/platform/wasm.zig
src/structs.zig

Implement some changes from #309

mach: implement some app changes

---

examples/advanced-gen-texture-light/main.zig
src/enums.zig
src/platform/native.zig
src/structs.zig

add mouse motion and mouse button events

---

src/platform/mach.js
src/platform/native.zig
src/platform/wasm.zig
src/structs.zig

mach: wasm: Implement mouse press, release, motion and scroll events

---

examples/advanced-gen-texture-light/main.zig
examples/boids/main.zig
examples/fractal-cube/main.zig
examples/gkurve/main.zig
examples/instanced-cube/main.zig
examples/rotating-cube/main.zig
examples/textured-cube/main.zig
examples/triangle/main.zig
examples/two-cubes/main.zig
shaderexp/main.zig
src/platform/common.zig
src/platform/mach.js
src/platform/native.zig
src/platform/wasm.zig
www/template.html

mach: App.update will not return bool and implement setShouldClose for wasm.

---

src/Engine.zig
src/platform/mach.js
src/platform/native.zig
src/platform/wasm.zig
www/template.html

add hasEvent(), waitEvent(), and waitEventTimeout()

---

examples/gkurve/LICENSE.tesselator
examples/gkurve/atlas.zig
examples/gkurve/data_structures/bit_array_list.zig
examples/gkurve/data_structures/compact.zig
examples/gkurve/data_structures/rb_tree.zig
examples/gkurve/label.zig
examples/gkurve/main.zig
examples/gkurve/resizable_label.zig
examples/gkurve/tessellator.zig
examples/gkurve/tracy.zig

About the tessellator code, the tessellator.zig and data_structures come from https://github.com/fubark/cosmic, the tracy code from the zig compiler

examples/gkurve: initial commit for resizable_label

---

freetype/src/freetype/GlyphSlot.zig
freetype/src/freetype/freetype.zig
freetype/src/harfbuzz/blob.zig
freetype/src/harfbuzz/buffer.zig
freetype/src/harfbuzz/font.zig

harfbuzz: more coverage

---

freetype/src/freetype/Glyph.zig
freetype/src/freetype/color.zig
freetype/src/harfbuzz/buffer.zig
freetype/src/harfbuzz/common.zig

harfbuzz: complete common binding

---

examples/gkurve/resizable_label.zig
freetype/examples/glyph-to-svg.zig
freetype/src/freetype/Outline.zig
freetype/src/harfbuzz/face.zig
freetype/src/harfbuzz/main.zig

harfbuzz: compelete face binding

---

glfw/src/main.zig

glfw: make MouseButton directly accessible, to match GLFW callback signature

---

src/Engine.zig
src/enums.zig
src/platform/mach.js
src/platform/native.zig
src/platform/wasm.zig

mach: mouse cursor support

---

freetype/build.zig
freetype/src/c.zig
freetype/src/freetype/Face.zig
freetype/src/freetype/Glyph.zig
freetype/src/freetype/GlyphSlot.zig
freetype/src/freetype/Library.zig
freetype/src/freetype/Outline.zig
freetype/src/freetype/Stroker.zig
freetype/src/freetype/color.zig
freetype/src/freetype/error.zig
freetype/src/freetype/freetype.zig
freetype/src/freetype/image.zig
freetype/src/freetype/lcdfilter.zig
freetype/src/freetype/main.zig
freetype/src/freetype/types.zig
freetype/src/harfbuzz/blob.zig
freetype/src/harfbuzz/buffer.zig
freetype/src/harfbuzz/c.zig
freetype/src/harfbuzz/common.zig
freetype/src/harfbuzz/face.zig
freetype/src/harfbuzz/font.zig
freetype/src/harfbuzz/main.zig
freetype/src/harfbuzz/shape.zig
freetype/src/harfbuzz/shape_plan.zig

harfbuzz: usable state

---

ecs/src/entities.zig

Allow size 0 (void) components. These can be used as flags allowing to iterate over entities with certain flags, but without the need to branch on the value of a bool/bitset, ~but there is an extra branch in the get/set functions~ the new branch in get/set should be comptime evaluated and not impose any overhead at runtime. This also doesn't add any per-entity storage overhead, but does add the overhead of new archetypes for each combination of void-components used.

ecs: allow components to have type void

---

build.zig
src/main.zig
src/resource/ResourceManager.zig
src/resource/uri_parser.zig

Foundation for #357 
Implements a basic resource management system with proper processing of resources. So far supporting only native backends. It doesn't contain grouping, wasm support, multithreading etc. and they will be part of a future PR.
Currently no example has been ported to this API, but it did worked with basic data lifetime and context testing.
---

mach: Begin resource management system

---

glfw/build.zig
glfw/src/Joystick.zig
glfw/src/Monitor.zig
glfw/src/clipboard.zig
glfw/src/key.zig
glfw/src/main.zig
glfw/src/opengl.zig

glfw: support compiling glfw with stage2

---

freetype/build.zig

depend to [this PR](https://github.com/hexops/freetype/pull/5)
once it get merged i will create a commit to update upstream

freetype: brotli support for woff2 fonts

---

gpu-dawn/build.zig
gpu-dawn/src/dawn/sample_utils.zig

gpu-dawn: support compiling with stage2 (-fno-stage1)

---

audio/build.zig

audio: make `buildSoundIo` private and point package to `./main.zig`

---

audio/build.zig
audio/examples/soundio-sine-wave.zig
audio/soundio/ChannelLayout.zig
audio/soundio/Device.zig
audio/soundio/OutStream.zig
audio/soundio/SoundIo.zig
audio/soundio/enums.zig
audio/soundio/main.zig
glfw/system_sdk.zig

audio: make soundio binding good enough to run sine-wave example

---

examples/textured-cube/main.zig
src/platform/native.zig

{mach, examples}: fix memory leaks

---

ecs/build.zig
ecs/src/entities.zig
ecs/src/main.zig
ecs/src/systems.zig

Best reviewed [with whitespace hidden](https://github.com/hexops/mach/pull/381/files?diff=unified&w=1).
This PR causes our ECS to be type-safe (the type safety here is mostly fully baked), and begin exploring message passing (this part is super early stages.)
This implements the type safety described in https://github.com/hexops/mach/pull/349 where you define head of time as part of an ECS _module_ what components you are defining. Then you may add/remove those components, or components from any other ECS module, to entities in the world at your choosing. The ECS world has a complete picture of all potential component types that will be used, and can thus enforce you are using the right type at comptime.
This is exploratory, the thought process is that message passing between systems …

ecs: type safety & message passing systems exploration

---

build.zig
examples/ecs-app/main.zig
examples/ecs-app/physics2d.zig
examples/ecs-app/renderer.zig
src/engine.zig
src/main.zig

Very early stages / experimental support for high-level ECS-based applications. This will be refined and improved in the near future, this is just to get *something* into `main` that we can begin iterating on.
This originates from https://github.com/hexops/mach/pull/349

Initial support for high-level ECS applications

---

freetype/build.zig
freetype/examples/glyph-to-svg.zig
freetype/examples/single-glyph.zig
freetype/src/freetype/Face.zig
freetype/src/freetype/Outline.zig
freetype/src/harfbuzz/buffer.zig
freetype/src/harfbuzz/common.zig
freetype/src/harfbuzz/shape.zig
freetype/src/harfbuzz/shape_plan.zig
freetype/test/main.zig

Two things I wanted to notice are, utils_pkg (see https://github.com/hexops/mach/issues/180#issuecomment-1175993008) and test_option, `@embedFile` can't import from `../` so we need to use `addOption` in the build file. Also we can't `@embedFile` in build.zig because when running build.zig for the first time upstream/ hasn't been downloaded yet.

freetype: support compiling with stage2 (-fno-stage1)

---

js-runtime/src/js-runtime.js
js-runtime/src/main.zig

Notable features:
- Calling constructor, eg ``new AudioContext()``
- String type in the same vein as Object and Function, renamed Value.value to Value.view
---

js-runtime: General improvements

---

audio/build.zig
audio/examples/soundio-sine-wave.zig
audio/soundio/Device.zig
audio/soundio/InStream.zig
audio/soundio/SoundIo.zig
audio/soundio/main.zig
audio/src/main.zig
audio/src/soundio.zig
freetype/src/freetype/Face.zig
freetype/test/main.zig

Audio: initial interface

---

ecs/src/entities.zig

Now that we have typed ecs components, it makes sense to get type safety into the query/iteration api. This is a first past that works, but I'm not thrilled with the api (passing the query to the `next()` function rather than the `query()` function that constructs the `Iterator`. To make the components a comptime parameter to `query()` instead of `next()` requires the information about the query to be stored in the iterator, which would mean `Iterator` has to be generic over the components queried. Alternatively the component query could be runtime information, but that would require allocating (to concatenate namespace and component name), or imposed a maximum length for namespace + component name.
How should the api for type-safe queries and iteration look? In the future when …

ecs: type-safe queries/iteration

---

build.zig
examples/LICENSE
examples/image-blur/blur.wgsl
examples/image-blur/fullscreen_textured_quad.wgsl
examples/image-blur/main.zig

hey! this is my first zig thing so feel free to provide the most feedback you can.
`filter_size`, `iterations` and `block_dimension` are hardcoded for now as the UI is being developed.

examples: add image-blur example

---

dev/update-zig.sh
freetype/src/freetype/main.zig
freetype/src/harfbuzz/main.zig
freetype/src/utils.zig
sysaudio/soundio/main.zig

added to stdlib via https://github.com/ziglang/zig/pull/12103

{freetype,sysaudio}: use `std.refAllDeclsRecursive`

---

build.zig
examples/LICENSE
examples/map-async/main.wgsl
examples/map-async/main.zig

examples: add map-async example

---

README.md

Stephen has recently created a Discord server to go alongside the Matrix chat one for people more used to Discord. I wish to add it to the README so people checking out the project can access it.

README add Discord Server

---

freetype/src/harfbuzz/buffer.zig

freetype/harfbuzz: getGlyphInfos() returns incorrect values

---

examples/gkurve/main.zig
examples/gkurve/resizable_label.zig

Gkurve leaks

---

.github/workflows/ci.yml
.github/workflows/m1_ci.yml
build.zig

CI: Improve job

---

dev/ci-lint.sh

 dev: add other workflows to ci-lint.sh

---

sysjs/build.zig

sysjs: pass target to `testStep`

---

src/platform/native.zig
src/structs.zig

Haven't tested it, getting an error on main
```
./src/platform/c.zig:1:15: error: C import failed
pub const c = @cImport({
^
./zig-cache/o/fb3e905d90ee2759b4b367d09520a121/cimport.h:3:10: note: 'dawn_native_mach.h' file not found
#include <dawn_native_mach.h>
```

mach: add headless option

---

src/platform/native.zig

Fixes https://github.com/hexops/mach/issues/453#issuecomment-1213006161

mach: use optional specifier

---

README.md

I don't know if it is caused by the change of GitHub page layout. The three GIFs cannot be displayed normally
I set the GIF width down so that it can align with the right side of the title

README: change the size of gif

---

glfw/build.zig

…hisDir() that works with stage1/stage2/stage3.

glfw: simplify build script, remove redundant allocs, improve -fno-stage1 support

---

glfw/README.md

"--build-dep" has been recently renamed to "--build_dep"
Signed-off-by: Eric Joldasov <bratishkaerik@getgoogleoff.me>

glfw: fix instructions for Gyro in README.md

---

build.zig
libs/basisu/build.zig
libs/freetype/.gitignore
libs/freetype/build.zig
libs/glfw/build.zig
libs/gpu-dawn/sdk.zig
libs/sysaudio/build.zig

all: improve build scripts, fix gamemode package path, improve gitignore

---

libs/basisu/build.zig
libs/freetype/src/Library.zig
libs/freetype/src/image.zig
libs/glfw/build.zig
libs/glfw/system_sdk.zig
libs/gpu-dawn/sdk.zig
libs/gpu/sdk.zig

freetype: complete *Scanline Converter* binding

---

libs/sysaudio/src/main.zig

sysaudio: soundio: Update tests to add needed allocator parameters

---

libs/sysaudio/build.zig

sysaudio: Link missing library for Windows

---

libs/sysaudio/soundio/InStream.zig
libs/sysaudio/soundio/OutStream.zig
libs/sysaudio/src/soundio.zig

sysaudio: soundio: Add missing bool param to call

---

libs/freetype/src/freetype.zig

Tests pass stage 1 & stage 2 with Windows 0.10.0-dev.3836+c5f1b3224

freetype: Update padding size of packed structs

---

libs/freetype/src/freetype.zig

freetype: Correct typo in previous fix

---

src/platform/native.zig

mach: supress gamemode dlopen failed error

---

build.zig
libs/gpu-dawn/sdk.zig
libs/gpu/build.zig

possibly not the best way to fix #464, but straightforward and it stopped filling up my storage.

gpu-dawn: default to release version of Dawn

---

build.zig
libs/freetype/build.zig
libs/glfw/system_sdk.zig
libs/sysaudio/build.zig

For >= 0.10.0-dev.3952+9e070b653

all: update to use latest Zig master APIs

---

build.zig
src/platform/native.zig
src/structs.zig

mach: add `is_app` option to disable gamemode in desktop applications

---

libs/glfw/src/Window.zig

glfw: don't reset hints after window creation

---

libs/gpu-dawn/sdk.zig

gpu-dawn: add mirror support for headers.json.gz

---

examples/advanced-gen-texture-light/main.zig
examples/cubemap/main.zig
examples/fractal-cube/main.zig
examples/gkurve/main.zig
examples/instanced-cube/main.zig
examples/map-async/main.zig
examples/pixel-post-process/main.zig
examples/rotating-cube/main.zig
examples/textured-cube/main.zig
examples/two-cubes/main.zig
shaderexp/main.zig
src/Core.zig
src/platform/libmach.zig
src/platform/native.zig
src/platform/wasm.zig

all: rename setShouldClose to close

---

.github/workflows/ci.yml
.github/workflows/m1_ci.yml
README.md
dev/template/.github/workflows/ci.yml
libs/basisu/.github/workflows/ci.yml
libs/freetype/.github/workflows/ci.yml
libs/glfw/.github/workflows/ci.yml
libs/glfw/.github/workflows/m1_ci.yml
libs/glfw/build.zig
libs/gpu-dawn/.github/workflows/ci.yml
libs/gpu-dawn/.github/workflows/m1_ci.yml
src/platform.zig
src/platform/wasm.zig

mach: check Platform functions declaration & add deinit for wasm

---

libs/basisu/build.zig

If we don't do that, we risk generating an invalid archive format for the cross-target.
---

basisu: pass CrossTarget to static libs

---

build.zig
libs/basisu/build.zig
libs/ecs/build.zig
libs/glfw/README.md
libs/glfw/build.zig
libs/gpu-dawn/build.zig
libs/gpu-dawn/sdk.zig
libs/gpu/build.zig
libs/gpu/sdk.zig
tools/wasmserve/wasmserve.zig

all: build: organize build files and reduce unreachables

---

libs/gamemode/build.zig

gamemode: `addIncludeDir` -> `addIncludePath`

---

build.zig
libs/basisu/build.zig
libs/ecs/build.zig
libs/freetype/build.zig
libs/freetype/src/main.zig
libs/gamemode/build.zig
libs/glfw/build.zig
libs/glfw/src/Window.zig
libs/gpu-dawn/sdk.zig
libs/gpu/sdk.zig
libs/sysaudio/sdk.zig
libs/sysjs/build.zig
tools/wasmserve/wasmserve.zig

all: build: thisDir improvements

---

.github/workflows/ci.yml
libs/freetype/src/Face.zig
libs/freetype/src/computations.zig
libs/freetype/src/harfbuzz/buffer.zig
libs/freetype/src/harfbuzz/font.zig
libs/freetype/src/main.zig

i patched upstream to fix the last error (https://gitlab.freedesktop.org/freetype/freetype/-/merge_requests/206)

freetype: fix compilation errors

---

examples/cubemap/cube_mesh.zig
examples/ecs-app/physics2d.zig
examples/ecs-app/renderer.zig
examples/fractal-cube/cube_mesh.zig
examples/gkurve/atlas.zig
examples/gkurve/draw.zig
examples/instanced-cube/cube_mesh.zig
examples/pixel-post-process/cube_mesh.zig
examples/pixel-post-process/main.zig
examples/pixel-post-process/quad_mesh.zig
examples/rotating-cube/cube_mesh.zig
examples/textured-cube/cube_mesh.zig
examples/two-cubes/cube_mesh.zig
libs/glfw/system_sdk.zig
src/platform/native.zig

examples: make sure some structs has guaranteed in-memory layout

---

libs/gpu-dawn/sdk.zig

gpu-dawn: strip debug info for release builds

---

libs/glfw/system_sdk.zig

system_sdk: better target check

---

libs/basisu/README.md
libs/freetype/README.md
libs/glfw/README.md
libs/gpu/README.md
libs/trimesh2d/README.md

all: README: fix links to main repository

---

libs/glfw/system_sdk.zig

glfw: system_sdk: bump max major linux version

---

build.zig

mach: build: fix init error type. append can return OutOfMemory

---

libs/gpu/examples/main.zig
shaderexp/main.zig

{shaderexp,gpu}: fix command buffer coercion

---

libs/freetype/src/color.zig
libs/freetype/src/freetype.zig
libs/freetype/src/harfbuzz/buffer.zig
libs/freetype/src/image.zig

freetype: set packed structs backing integer

---

.gitattributes

gitattributes: update linguist-vendored C code marking

---

build.zig

mach: fix missing param when linking model3d

---

libs/ecs/src/entities.zig

ecs: rename sort function to be camelCase

---

src/gfx/util.zig

mach: gfx: Add VertexWriter

---

src/gfx/util.zig
src/main.zig

Fixes some mistakes in VertexWriter and exposes it in the mach api.

mach: VertexWriter fixes

---

build.zig

handle error union in build.zig

---

libs/glfw/src/Joystick.zig
libs/glfw/src/Monitor.zig
libs/glfw/src/Window.zig

glfw: update to zig 0.11.0-dev.811

---

libs/ecs/src/entities.zig

ecs: improve formatting

---

libs/ecs/src/entities.zig
libs/ecs/src/systems.zig
libs/sysaudio/src/main.zig

I changed some stuff that didn't allowed me to build mach-examples (`zig build`) on `0.11.0-dev.923+a52dcdd3c`, very similar to previous PR. I was not sure about removing  `.layout = .Auto` as i have no idea about what it does, but it does fix the build.

fix compiler errors regarding zig changes

---

build.zig
libs/gpu-dawn/.github/workflows/ci.yml
libs/gpu-dawn/sdk.zig

build: replace App.setBuildMode() with `mode` option

---

libs/gpu/build.zig
libs/gpu/examples/sample_utils.zig

Decided to try since I was bored, turned out to be pretty easy. Don't know if it's even worth merging but ¯\\\_(ツ)\_/¯
Fixes: #659

gpu: fix example build

---

.github/workflows/ci.yml
dev/template/.github/workflows/ci.yml
libs/basisu/.github/workflows/ci.yml
libs/earcut/.github/workflows/ci.yml
libs/freetype/.github/workflows/ci.yml
libs/glfw/.github/workflows/ci.yml
libs/gpu-dawn/.github/workflows/ci.yml
libs/gpu-dawn/sdk.zig
libs/gpu/examples/sample_utils.zig
src/platform/native/util.zig

We still have to update dawn version to get wayland working

gpu-dawn: mach side wayland support

---

libs/gpu/build.zig
libs/gpu/examples/main.zig
libs/gpu/examples/sample_utils.zig

Update the mach/gpu only example to work with the latest zig and recent glfw error handling changes.

gpu: Update example to latest zig/glfw

---

libs/ecs/src/entities.zig
libs/glfw/build.zig
libs/gpu-dawn/sdk.zig
src/engine.zig

gpu-dawn: fix {linux,windows}->macos cross-compilation

---

src/platform/native/Core.zig

mach: re-create swapchain on vsync mode change

---

libs/freetype/.github/workflows/ci.yml
libs/glfw/.github/workflows/ci.yml
libs/glfw/.github/workflows/m1_ci.yml
libs/glfw/system_sdk.zig
libs/gpu/.github/workflows/ci.yml
libs/sysaudio/sdk.zig
libs/sysaudio/src/alsa.zig
libs/sysaudio/src/backends.zig
libs/sysaudio/src/dummy.zig
libs/sysaudio/src/jack.zig
libs/sysaudio/src/main.zig
libs/sysaudio/src/pipewire.zig
libs/sysaudio/src/pipewire/sysaudio.c
libs/sysaudio/src/pulseaudio.zig
libs/sysaudio/src/wasapi.zig
libs/sysaudio/src/wasapi/win32.zig
libs/sysaudio/src/webaudio.zig
src/platform/wasm/entry.zig

Helps #682 
Fixes #680
Fixes #649
see also:
- https://github.com/hexops/sdk-linux-x86_64/pull/7
- https://github.com/hexops/sdk-linux-aarch64/pull/5

sysaudio: pipewire backend

---

build.zig
libs/sysaudio/src/pipewire.zig
libs/sysaudio/src/webaudio.zig

some improvements

---

build.zig
libs/core/build.zig
libs/core/include/libmachcore.h
libs/core/sdk.zig
libs/core/src/main.zig
libs/core/src/platform/libmachcore.zig

This change includes a few of the initial changes needed for [mach-rs](https://github.com/hexops/mach-rs/).
https://github.com/hexops/mach/issues/391

core: libmachcore fixes

---

libs/glfw/src/Window.zig

Note: This is only supported on latest zig master.

glfw: update to new for loop syntax

---

libs/basisu/src/transcoder.zig
libs/ecs/src/entities.zig
libs/ecs/src/systems.zig
libs/glfw/src/Window.zig
libs/glfw/src/vulkan.zig
libs/model3d/src/main.zig
libs/sysaudio/src/alsa.zig
libs/sysaudio/src/jack.zig
libs/sysaudio/src/main.zig
libs/sysaudio/src/pipewire.zig
libs/sysaudio/src/pulseaudio.zig
libs/sysaudio/src/wasapi.zig
libs/sysaudio/src/wasapi/win32.zig
libs/sysaudio/src/webaudio.zig
tools/wasmserve/wasmserve.zig

This PR include two fixes: 
1. createWindowSurface was returning VK_NOT_READY  (1) because of some old code which converted the VkResult int to a bool.
2. run `zig fmt .` in  project root to update to new zig for loop syntax

all: fix issue with glfw vulkan createWindowSurface; update to new for loop syntax

---

libs/dusk/src/Ast.zig
libs/dusk/src/AstGen.zig
libs/dusk/src/IR.zig
libs/dusk/src/Parser.zig
libs/dusk/test/main.zig

dusk: rewrite AstGen.zig and IR.zig

---

build.zig
libs/basisu/build.zig
libs/core/sdk.zig
libs/dusk/build.zig
libs/ecs/build.zig
libs/freetype/build.zig
libs/model3d/build.zig
libs/sysaudio/sdk.zig
tools/wasmserve/wasmserve.zig

all: build: update to zig version 0.11.0-dev.6883+da0509750

---

libs/dusk/src/AstGen.zig
libs/dusk/src/IR.zig
libs/dusk/test/boids.wgsl
libs/dusk/test/main.zig

dusk: abilibity to reference global decl after current decl

---

libs/ecs/README.md
libs/ecs/src/main.zig
libs/ecs/src/systems.zig
src/engine.zig
src/main.zig

This makes various improvements to the mach/ecs module system.

{mach,ecs}: various ECS module system improvements

---

libs/basisu/src/encoder.zig
libs/basisu/src/transcoder.zig
libs/core/src/Core.zig
libs/core/src/platform/wasm/Core.zig
libs/core/src/platform/wasm/mach.js
libs/glfw/src/hat.zig
libs/glfw/src/mod.zig
libs/gpu/src/buffer.zig
libs/gpu/src/texture.zig
libs/gpu/src/types.zig
libs/model3d/src/main.zig

core: get examples working on wasm target again

---

libs/sysaudio/src/alsa.zig
libs/sysaudio/src/backends.zig
libs/sysaudio/src/coreaudio.zig
libs/sysaudio/src/dummy.zig
libs/sysaudio/src/jack.zig
libs/sysaudio/src/main.zig
libs/sysaudio/src/pipewire.zig
libs/sysaudio/src/pulseaudio.zig
libs/sysaudio/src/wasapi.zig
libs/sysaudio/src/webaudio.zig

sysaudio: initial macOS support (CoreAudio)

---

README.md

readme: remove the extra closing parenthesis

---

.github/workflows/ci.yml
.github/workflows/m1_ci.yml
.github/workflows/push_subrepos.yml

ci: make ci run selectively

---

libs/freetype/src/harfbuzz/main.zig

Like in `freetype/src/main.zig`.

harfbuzz: expose C API

---

libs/dusk/build.zig
libs/dusk/src/Ast.zig
libs/dusk/src/AstGen.zig
libs/dusk/src/IR.zig
libs/dusk/src/Parser.zig
libs/dusk/src/Tokenizer.zig
libs/dusk/src/main.zig
libs/dusk/src/print_ir.zig
libs/dusk/test/main.zig

dusk: AstGen expressions

---

libs/freetype/src/harfbuzz/main.zig
libs/freetype/src/main.zig

{freetype, harfbuzz}: fix build error

---

libs/model3d/src/main.zig

model3d: use std.c.free to free save result

---

app/Builder.zig

fixes #739
In my testing it builds like in the fork/exec implementation. But I couldn't get any of the examples to run under wasm, even under the old implementation.

app: Use std.ChildProcess instead of POSIX calls

---

libs/core/sdk.zig

core: add @panic when target is wasm

---

.gitmodules
build.zig
dev/push-subrepos.sh
libs/basisu/.gitmodules
libs/basisu/build.zig
libs/core/build.zig
libs/core/sdk.zig
libs/dusk/build.zig
libs/earcut/build.zig
libs/ecs/build.zig
libs/freetype/build.zig
libs/freetype/src/image.zig
libs/glfw/build.zig
libs/gpu-dawn/build.zig
libs/gpu-dawn/sdk.zig
libs/gpu/build.zig
libs/gpu/sdk.zig
libs/model3d/build.zig
libs/sysaudio/build.zig
libs/sysaudio/sdk.zig
libs/sysjs/build.zig

update to latest Zig version; fix submodule locations

---

libs/ecs/src/entities.zig
libs/ecs/src/main.zig
libs/ecs/src/query.zig

ecs: query support

---

libs/sysaudio/build.zig
libs/sysaudio/examples/sine-wave.zig
libs/sysaudio/sdk.zig
libs/sysaudio/src/alsa.zig
libs/sysaudio/src/backends.zig
libs/sysaudio/src/coreaudio.zig
libs/sysaudio/src/main.zig
libs/sysaudio/src/pulseaudio.zig
libs/sysaudio/src/wasapi.zig

sysaudio: improve backend selection; remove i8 sample support

---

libs/core/sdk.zig

less than ideal so only a temporary fix

core: fix windows release build issues by disabling LTO

---

libs/glfw/src/main.zig

glfw: rename duplicate test name (test.pollEvents)

---

libs/sysaudio/examples/sine-wave.zig
libs/sysaudio/src/coreaudio.zig
libs/sysaudio/src/main.zig

sysaudio: simplify channel logic for coreaudio (fixes macOS usage)

---

libs/glfw/src/Window.zig

glfw: set raw_mouse_motion to true if cursor is disabled

---

src/gfx2d/Sprite2D.zig

Addresses issue https://github.com/hexops/mach/issues/803

gfx2d: fix Sprite2D Uniforms binding size

---

libs/gpu/README.md
libs/gpu/src/adapter.zig
libs/gpu/src/bind_group.zig
libs/gpu/src/bind_group_layout.zig
libs/gpu/src/buffer.zig
libs/gpu/src/compute_pass_encoder.zig
libs/gpu/src/dawn.zig
libs/gpu/src/dawn_impl.zig
libs/gpu/src/device.zig
libs/gpu/src/instance.zig
libs/gpu/src/interface.zig
libs/gpu/src/main.zig
libs/gpu/src/pipeline_layout.zig
libs/gpu/src/query_set.zig
libs/gpu/src/queue.zig
libs/gpu/src/render_bundle.zig
libs/gpu/src/render_bundle_encoder.zig
libs/gpu/src/render_pass_encoder.zig
libs/gpu/src/sampler.zig
libs/gpu/src/shader_module.zig
libs/gpu/src/swap_chain.zig
libs/gpu/src/texture.zig

updates the `gpu.Interface` to the latest Dawn API: https://github.com/hexops/mach/pull/812

gpu: update to latest webgpu.h API

---

libs/gpu/src/buffer.zig
libs/gpu/src/device.zig
libs/gpu/src/queue.zig

mach-gpu: update to latest zig API

---

src/main.zig
src/math.zig

I expanded Math Lib with a few functions and tests.
I added:
- `rotateX(angle_radians: f32) Mat4x4` and 
- `rotateY(angle_radians: f32) Mat4x4`, both of them follow similiar style as existing `rotateZ`
- `set_2d_matrix(data: []const f32) Mat3x3` and 
- `set_3d_matrix(data: []const f32) Mat4x4` to set matrix to whatever values you have in 9 and 16 long arrays.  This function is similar to [wgpu-matrix mat4.set.](https://wgpu-matrix.org/docs/functions/mat4.set.html)
- `equals(a: anytype, b: @TypeOf(a)) bool` and 
- `equalsApproximately(a: anytype, b: @TypeOf(a), tolerance: f32) bool ` to easier test if two matrices are equal or close to equal. This was helpful when testing outcomes of other operations in tests. wgpu-matrix library has the same two methods …

mach: math lib adding functionality and tests

---

build.zig

warn if user zig version is out of date

---

.gitmodules
build.zig
build.zig.zon

build: depend on mach-freetype via package manager

---

build.zig
build.zig.zon

build: also depened on hexops/freetype

---

src/editor/app.zig
src/editor/main.zig
src/engine.zig
src/main.zig

update to latest mach-core API

---

src/engine.zig

engine: init device

---

src/math/mat.zig

math: add more tests

---

src/math/vec.zig

math: Add additional Vec operations

---

src/math/mat.zig

Perspective Matrix

---

src/gfx/Text.zig

The text example noted that the second string would cause a panic if it was a different size. This was because the Text module was checking if a codepoint was already rendered before, but not if that codepoint was in the correct font or size.
My fix is to turn the `RegionMap` hashmap's key into a struct with the appropriate values.

text: Fixed atlas finding glyphs of wrong size

---

src/math/ray.zig

Early return with null for a ray with no direction

---

build.zig
examples/core-custom-entrypoint/Game.zig
examples/core-custom-entrypoint/main.zig
examples/core-custom-entrypoint/shader.wgsl
examples/custom-renderer/Game.zig
examples/custom-renderer/Renderer.zig
examples/custom-renderer/main.zig
src/Core.zig
src/core/main.zig
src/core/platform/glfw/Core.zig
src/main.zig
src/module/module.zig

core: add mach.Core module API

---

src/sysaudio/alsa.zig
src/sysaudio/coreaudio.zig
src/sysaudio/main.zig
src/sysaudio/pulseaudio.zig
src/sysaudio/wasapi.zig

sysaudio: disable i24 sample format

---

src/sysgpu/shader/codegen/spirv.zig

spirv: sqrt instruction

---

build.zig
build.zig.zon
examples/play-opus/App.zig
examples/play-opus/main.zig

add play-opus example

---

src/sysaudio/alsa.zig
src/sysaudio/conv.zig
src/sysaudio/coreaudio.zig
src/sysaudio/main.zig
src/sysaudio/pulseaudio.zig
src/sysaudio/wasapi.zig

sysaudio: revive i24 samples

---

src/math/collision.zig
src/math/main.zig

math: collision module

---

src/sysgpu/d3d12.zig

Fixes https://github.com/hexops/mach/issues/1218

Buffer resources from swap chain were not being released.

---

build.zig
src/Core.zig
src/core/darwin.zig
src/main.zig

This is the smallest change I could make to get the `run-triangle` demo working on macOS. We can rework this significantly over time but this should at least unblock ongoing development.

Initialize macOS app delegate and set up a Metal view

---

src/core/darwin.zig
src/sysgpu/metal.zig

This updates to the new APIs from https://github.com/hexops/mach-objc/pull/17

Use the new Block APIs

---

src/sysgpu/d3d12.zig

Show warning instead of panic when debug layer cant be created #1128

---

build.zig

build: add docs build step

---

src/math/mat.zig

Implement `.eql()` and `.eqlApprox()` methods for matrices. The previous implementation only supported a single method for comparing matrices, but I thought it might be useful to include two methods, one that uses elipson tolerance and another that uses user-defined tolerance, just like how `Vector`s currently handle it.
I felt it was redundant to include tests for 2x2 and/or 3x3, but let me know if you want me to add those.

Implement `MatShared.eql()` and `MatShared.eqlApprox()` methods

---

src/math/collision.zig

* Added function to compute contacts between polygons and circles.
* Added documentation for existing functions.
* Fixed a bug in Line.collideLine.
* Added more unit tests.
Related to #1243

Updates to math.collision

---

.github/workflows/ci.yml
src/core/Linux.zig
src/core/linux/X11.zig

core: get x11 to build

---

src/sysgpu/utils.zig

`@fence()` was removed from ziglang in https://github.com/ziglang/zig/pull/21585
Following the guidance they provided,
`@fence()` was removed and replaced with an atomic u32 value which uses an acquire to sync with previous releases.

remove: @fence()

---

build.zig
build.zig.zon

This PR is meant to be paired with: https://github.com/hexops/wayland-headers/pull/17

Add libdecor

---

src/Core.zig
src/core/linux/X11.zig

core: x11: clarify X11 multi-threading

---

src/core/Linux.zig
src/core/linux/Wayland.zig
src/core/linux/X11.zig

core: clean linux up a bit

---

src/core/Linux.zig
src/core/linux/Wayland.zig
src/core/linux/X11.zig

core: implement `Linux.setTitle()`

---

examples/core-custom-entrypoint/App.zig
examples/core-triangle/App.zig
src/Core.zig
src/core/Darwin.zig
src/module.zig

obj: Allow tracking of individual struct fields for changes

---

src/core/Linux.zig
src/core/linux/Wayland.zig
src/core/linux/X11.zig

Right now, it builds but does not run. Working on getting it to run.

linux: get build working with new system

---

src/Core.zig
src/core/Windows.zig

Get windows back running

---

build.zig
build.zig.zon
examples/core-transparent-window/App.zig
examples/core-transparent-window/main.zig
examples/core-transparent-window/shader.wgsl
src/Core.zig
src/core/Darwin.zig
src/sysgpu/metal.zig

Currently this PR just gets titles working back on Darwin, as well as temporarily setting all window backgrounds to 0.5 alpha to test transparency. We will need to add some fields to `core.windows` to control these values per-window.

Attempt to get an example of a transparent window working

---

src/sysgpu/shader/codegen/spirv.zig

Fixed an issue causing a miscompiled shader in the hardware-test example on Linux.

Fixed spir-v generation in hardware test example

---

src/core/Linux.zig
src/core/linux/Wayland.zig
src/core/linux/X11.zig
src/gamemode.zig

Revert changes of 41ddd22 so `std.DynLib.open` is used to load dyn libs instead of `mach.dynLibOpen` because we want to silently fail. Also improve logging if both x11 and wayland fail:

gamemode: revert commit 41ddd22 for gamemode.zig

---

build.zig.zon

core: Update to latest mach-objc

---

src/math/mat.zig
src/math/vec.zig

Resolves issue #1240. Always nice to be able to print things for debugging.

Add format function for vector and matrix types.

---

src/math/mat.zig

Added rotation matrix generation from quaternion as request on issue
Closes #1318

Add matrix rotation by quaternion

---

src/sysaudio/main.zig

Displays the selected sysaudio backend as a log message.
It also displays if a backend failed to initialize, which one it was.

display which audio-backend got selected
