hexops/mach

.github/workflows/ci.yml
.github/workflows/m1_ci.yml
glfw/build.zig

Adds full cross compilation support, via a small Linux SDK (~27M) that is `git clone`d in `build.zig`:
https://github.com/hexops/sdk-linux-x86_64
Enables cross compilation from any OS to Linux, and removes the need to install any dependencies other than `zig` and `git` to build on Linux.

Add Linux SDK & cross compilation support

---

glfw/src/action.zig

A very minor fix to correct ``key.press`` being set to ``GLFW_RELEASE``  instead of ``GLFW_PRESS``

fix key.press being set to release

---

.github/workflows/ci.yml
glfw/.github/workflows/ci.yml
glfw/build.zig

Brings us up-to-date with latest Zig and works around an issue. Introduces #48

update to Zig nightly 1444+e2a2e6c14

---

glfw/src/opengl.zig
glfw/src/vulkan.zig

Having `glfw.getProcAddress` conform to the GLFW C ABI is important as it is often
likely to be passed into libraries which expect exactly that ABI for OpenGL function
loading.
Fixes #52

glfw: make glfw.getProcAddress conform to GLFW C ABI 

---

glfw/src/Joystick.zig
glfw/src/Window.zig
glfw/src/action.zig
glfw/src/key.zig
glfw/src/main.zig
glfw/src/mod.zig

Make the GLFW action enumerations proper Zig enums so one can use `.Name` syntax, etc.
Helps #37

glfw: ziggify all Action enums

---

glfw/build.zig
glfw/system_sdk.zig

This refactors the logic for system SDK inclusion out of the GLFW-specific `build.zig`,
and should make it very easy for anyone to copy this file and start getting cross-platform
builds of their own OpenGL/Vulkan Zig projects.
There may be some libraries we need to add for Vulkan to these SDKs, I haven't yet tested
that - but the overall idea here seems sound.
Fixes #39

glfw: refactor system SDK inclusion into helper file

---

glfw/build.zig

This effectively gives us the dependencies we need in any case, and works around ziglang/zig#10103
Importantly, this removes a blocker for landing WebGPU support in hexops/mach#62

glfw: fix linking difference between sysroot and non-sysroot

---

glfw/README.md

When changes are merged to both hexops/mach and hexops/mach-glfw, we get a conflict
which is difficult to resolve with `git subtree`, particularly because we don't want
to squash commits for either repository (we prefer to maintain the full commit history
in both repos.)
Instead, require that all pull requests be sent to the main hexops/mach repository.
That's not as nice, I admit, but should be pretty easy to handle (literally just copy
changes over) and will ensure we can always keep both repos in sync easily and without
conflict.

glfw: send pull requests to the main repository to avoid merge conflicts

---

glfw/README.md
glfw/src/Cursor.zig
glfw/src/Joystick.zig
glfw/src/Monitor.zig
glfw/src/Window.zig
glfw/src/clipboard.zig
glfw/src/key.zig
glfw/src/main.zig
glfw/src/opengl.zig
glfw/src/time.zig
glfw/src/vulkan.zig

Closes #66
What should be done with the original `InitHint` enum and `initHint` function could maybe be discussed. I didn't remove them, as they were useful for implementing the new interface, and make it so that new code behaves about the same way as old code which explicitly set all hints. They are also documentative, seeing as they more closely reflect the actual GLFW API than these changes.

Friendlier GLFW API initialization

---

glfw/src/Window.zig

Closes #69, and applies the same thought to other parts of the API. Also fixes some stray comments which should be doc comments.

glfw: Small Window fixes

---

glfw/upstream/glfw/src/x11_window.c

Pressing any given modifier key twice caused ubsan crashes on X11

glfw: patch more undefined behaviour

---

glfw/README.md
glfw/src/Window.zig
glfw/src/consts.zig
glfw/src/main.zig
glfw/src/opengl.zig

~~I took a different approach to the one used for initialization hints, because I realized that it would probably a lot of overhead to call `Window.hint` for every possible hint, compared to how status quo allows one to avoid that overhead; as well, it would probably be a lot harder to maintain, given that, unlike `InitHint`, window initialization hints are of more types than just booleans.~~
~~This approach is (quite a bit) more verbose, but avoids the overhead, and probably makes it easier to maintain.~~
Also, I found that `context_revision` and `context_no_error` are listed in `Window.Hint`, but are not listed as hints in the docs, only as attributes; I commented them out to make what I have pass tests - is this intentional and I'm missing something, or is this the result of some …

glfw: Window hints rework

---

glfw/src/Joystick.zig
glfw/src/Monitor.zig
glfw/src/Window.zig
glfw/src/clipboard.zig
glfw/src/key.zig
glfw/src/main.zig
glfw/src/opengl.zig
glfw/src/vulkan.zig

Just makes the API a bit nicer to use from Zig. According to the [Zig docs](https://ziglang.org/documentation/master/#toc-C-Pointers) `[*c]` pointers should be avoided, and should be replaced with more precise pointer types wherever possible

glfw: remove [*c] pointers from api and return lengthed strings when possible

---

glfw/src/Cursor.zig

Following a similar change made to types in 'Window.zig'

glfw: make `glfw.Cursor.Shape` public

---

glfw/src/Window.zig

Compared to `Window.Hint`, where some comments were worth keeping, all comments within `Window.Attribute` appear to be basically redundant.

glfw: reorganize `Window.Attrib` to be in the same style as `Window.Hint`

---

glfw/system_sdk.zig
glfw/upstream/glfw/src/cocoa_platform.h

Updates us to using the newer SDK https://github.com/hexops/sdk-macos-12.0
Also enables cross-compilation of the `mach/gpu` backend for macOS.

glfw: update system_sdk to use latest MacOS 12.0 SDK

---

glfw/src/errors.zig

Bring back the 'c.GLFW_NOT_INITIALIZED' prong in 'convertError', such that if it is ever passed that error code, we can differentiate it from just an invalid input; because it is an valid input, we just guarantee that it won't occur.

glfw: re-instate prong

---

glfw/src/clipboard.zig

Add 'FormatUnavailable' as a possible error to the 'getClipboardString' comment, which can set it on wayland.
I made a pull request upstream for the same change: https://github.com/glfw/glfw/pull/1998
This is already reflected in the catch block for 'getError()', which caught this in the CI for #92.

glfw: update possible errors comment

---

glfw/src/Window.zig

Turns out I combed through the codebase the first time pretty well, only found one function that didn't have the appropriate `internal_debug.assertInitialized()` statement.

glfw: Force init follow up

---

glfw/src/Cursor.zig
glfw/src/Joystick.zig
glfw/src/Window.zig
glfw/src/errors.zig
glfw/src/key.zig
glfw/src/main.zig

An initial effort to eliminate the need for `InvalidEnum`; there are a couple of places preventing straight removal of the error, so I'll have a look at the GLFW source to see if they can be omitted safely.

glfw: Eliminate `InvalidEnum`

---

glfw/src/Joystick.zig
glfw/src/Monitor.zig
glfw/src/Window.zig
glfw/src/main.zig
glfw/src/opengl.zig
glfw/src/time.zig
glfw/src/vulkan.zig

Closes #101.
As will be noted, the actual error hasn't been deleted, but measures have been taken such that it will never be encountered as an error by the user, save for in the case of `Joystick.updateGamepadMappings`, which will be changed to have its own error `ParseError` later on, when errors are denormalized.

glfw: Eliminate `Error.InvalidValue`

---

glfw/src/time.zig

Make the constant extracted from GLFW source into `time.setTime`, into a better-documented set of comptime instructions

glfw: un-hardcode constant

---

glfw/build.zig

This removes a linker hack which was preventing building with the latest
Zig master version. Of particular note, anyone wishing to use this library
will need to ensure they are up to date with latest master.
The binary releases available at https://ziglang.org/download/ (1783+eec825c and
beyond) are sufficient (really, anything released after today.)
Fixes hexops/mach#103

glfw: support building with latest Zig master

---

.github/workflows/ci.yml
glfw/.github/workflows/ci.yml
glfw/build.zig
glfw/src/Window.zig
glfw/src/opengl.zig
glfw/system_sdk.zig
glfw/upstream/glfw/src/cocoa_platform.h

The latest Zig master supports specifying a specific macOS version for libc, via
the target triple (ziglang/zig#10215):
* x86_64-macos.10 (Catalina)
* x86_64-macos.11 (Big Sur)
* x86_64-macos.12 (Monterey)
* aarch64-macos.11 (Big Sur)
* aarch64-macos.12 (Monterey)
Mach's `system_sdk.zig` can now download the relevant XCode framework stubs for Big Sur (11) and Monterey (12). Although we don't have an SDK for Catalina (10) currently, we use the Big Sur (11) SDK in that case and it generally works fine.
By default, Zig targets the N-3 version (e.g. `x86_64-macos` defaults to `x86_64-macos.10`).
Targeting the minimum supported version is useful for compatability, it guarantees the produced binary will run on any later macOS version. Targeting the newer version can be useful if you wish to use …

glfw: update system_sdk to match latest Zig master macOS version targeting

---

glfw/system_sdk.zig

This brings various improvements to the way we use native system SDKs:
1. Fixed a bug where the Apple SDK license prompt would not appear for older SDKs.
2. We now pin and auto-update SDK versions, see commit message for details: https://github.com/hexops/mach/commit/dfcfb5ba4851af8bd3485dfdd94ea1a7af1fdc9c
Helps hexops/mach#108

glfw: system_sdk version pinning, automatic updates, and correctex Apple license prompt

---

glfw/src/vulkan.zig

The GLFW implementation takes a constant pointer to a `VkAllocationCallbacks` struct; casting it to a mutable pointer equivalent here doesn't break anything, but does prevent passing a valid const pointer, which is often what one should prefer to do.
As well, the `@alignOf` builtin takes the alignment expected of the type directly, so `@alignOf(*T)` returns the alignment of `*T`, not `T`, so that has also been corrected.

glfw: Fix pointer cast

---

glfw/src/Cursor.zig
glfw/src/Joystick.zig
glfw/src/Monitor.zig
glfw/src/Window.zig
glfw/src/clipboard.zig
glfw/src/errors.zig
glfw/src/key.zig
glfw/src/main.zig
glfw/src/opengl.zig
glfw/src/time.zig
glfw/src/vulkan.zig

Tests pass on my machine, and everything seems fine; added a TODO note concerning what looks like a memory leak in 'Window.zig'. If there's discussion to be had, I'll turn this into a draft, but otherwise I feel like it's ready to merge. 
Also brought back errors that had been deleted in the 'Error' error set, and wrote out some unreachable paths that were previously implicitly unreachable, being that the Error error set is no longer forwarded uniformly; adds some documentative value. 
Closes #96.

glfw: Denormalize errors

---

glfw/src/Window.zig

Change some parameters in `glfw.Window` functions to accept null in place of `glfw.dont_care` as a sentinel value.
Closes #119.
This is a quick change, but there are other places where `glfw.dont_care` is an accepted value to ask for "default behavior", such as in hints; should we also change those to be null-able, or leave them as is?

glfw: replace usage of glfw.dont_care as sentinel value

---

glfw/build.zig
glfw/src/Window.zig
glfw/src/sources_all.c
glfw/src/sources_linux.c
glfw/src/sources_linux_wayland.c
glfw/src/sources_linux_x11.c
glfw/src/sources_macos.c
glfw/src/sources_macos.m
glfw/src/sources_windows.c

This consistently shaves off about 40ms (~130ms -> ~90ms, 30% reduction) from build times when iterating.
On Windows, I suspect the result will be much greater due to slow filesystem perf there and the fact that this reduces the # of files read.
This was originally brought to my attention as a possibility by @meshula in hexops/dawn#2, the way this works is by reducing compilation units so that C headers only need to be read/parsed/interpreted once rather than once per individual C source file we are compiling.

glfw: reduce compilation units to bring iteration time down to ~90ms

---

gpu/src/dawn/hello_triangle.zig

The dawn example currently wasnt compiling because the parameter type of glfw's framebuffer callback was incorrect. This was a leftover from #126 
Feel free to close it if already done locally.

gpu: Fix invalid parameter type of glfw framebuffer callback function

---

glfw/src/errors.zig
glfw/src/main.zig

glfw: expose glfwSetErrorCallback for retrieving optional error descriptions

---

glfw/src/Window.zig

This change both restricts and clarifies the mutability/nullability of the pointers, and replaces the explicitly-typed pointer usage in setUserPointer with ?*anyopaque, since it now, as of being renamed from c_void, more simply communicates the intent of taking any pointer type.

glfw: Tidy up UserPointer access

---

gpu-dawn/src/dawn/hello_triangle.zig

@slimsag this PR fixes the `gpu-dawn/hello_triangle` example. All the build steps in `gpu-dawn/build.zig` are working for me now (tested on MacOS only). Not 100% sure I understand the pointer usage, but it seems to work for me.
Reference issues:
- https://github.com/hexops/mach/issues/153
- https://github.com/hexops/mach/pull/152

gpu-dawn: update to latest glfw get/setUserPointer API introduced in hexops/mach#152

---

glfw/src/vulkan.zig

Using an inline `opaque{}` type forces the use of `@typeInfo` to cast to the specific type of the parameter.

glfw: Use `anyopaque` instead of `opaque{}`

---

ecs/README.md
ecs/build.zig
ecs/src/main.zig

This is the very, _very_, early stages of an entity component system for Mach. It's not ready for any real use, but rather is a starting point for further development.
This spawned after [this research issue](https://github.com/hexops/mach/issues/127) in which I got tons of great information, tips, etc. and after much more research after that discussion this is what I've landed on _initially_. I'm positive this will change dramatically in the coming weeks/months, the idea is to use this just as a starting point and continue molding it into what we want.
As development continues..
* I've created [a room in the Matrix server for anyone who wants to chat](https://matrix.to/#/#ecs:matrix.org)
* We can file and discuss in GitHub issues.
* I'll be maintaining a blog detailing everything I've …

ecs: add very early-stages entity component system

---

ecs/README.md
ecs/src/main.zig

I promised the next blog post in the series would be code, not verbal explanation like this, so I'll likely allude to all of this (and link to this explanation) for how my thinking has developed since the last article. Then it will focus on the code here.
Previously, we had thought about our ECS in terms of archetypes defined at compile time (effectively arrays of archetype structs with comptime defined fields as components.) I believe that this is likely *the most efficient* way that one could ever represent entities. However, it comes with many limitations, namely that:
You have to define which components your entity will have _at compile time_: with our implementation, adding/removing components to an entity at runtime was not possible (although declaring components at comptime that …

ecs: major rethink & database-aligned design

---

glfw/src/Cursor.zig
glfw/src/Joystick.zig
glfw/src/Monitor.zig
glfw/src/Window.zig
glfw/src/clipboard.zig
glfw/src/key.zig
glfw/src/main.zig
glfw/src/native.zig
glfw/src/opengl.zig
glfw/src/time.zig
glfw/src/vulkan.zig

A large chunk of glfw functions inform us of success using their return values, that means that calling `getError` is unnecessary in those cases.
The cost of `getError` (for the non-error case) is more than the single branch checking the return value:
1. call to `glfwGetError`
1. check `description` pointer
2. platform tls lookup
3. check error is not `GLFW_NO_ERROR`
2. switch from int to error in `convertError`

glfw: dont call `getError` unless we need to

---

glfw/src/Cursor.zig
glfw/src/Joystick.zig
glfw/src/Monitor.zig
glfw/src/Window.zig
glfw/src/clipboard.zig
glfw/src/key.zig
glfw/src/main.zig
glfw/src/native.zig
glfw/src/opengl.zig
glfw/src/vulkan.zig

In safe build modes `@errSetCast` emits *runtime* checks to validate the error is in the destination errorset.
As switches do errorset narrowing automatically `@errSetCast` is unnecessary and validation of the error being in the errorset occurs at compile time.

glfw: dont use `@errSetCast`

---

glfw/src/Joystick.zig
glfw/src/Monitor.zig
glfw/src/Window.zig
glfw/src/errors.zig
glfw/src/opengl.zig

This PR changes the way glfw callback functions are implemented.
**Before**
Inside Window.zig `from` there is an allocation of a `InternalUserPointer` with an allocator not explicitly provided by the caller.
**After**
No hidden allocation anywhere. (atleast in the zig wrapper's code)
**Before**
Due to using the user pointer functionality provided by glfw to carry around function callbacks, the API to work with the end users actual user pointer generates more code.
**After**
`getUserPointer` & `setUserPointer` are trivial passthrough functions.
**Before**
When an event occurs that the user has set a callback for the below takes place before the users callback code is reached:
- call through a runtime function pointer from glfw to a callback wrapper
- call back into glfw to get the …

glfw: use comptime magic to remove `InternalUserPointer` and associated overhead

---

.gitmodules
gpu-dawn/.gitmodules
gpu-dawn/build.zig
gpu-dawn/src/dawn/dawn_native_mach.cpp
gpu-dawn/src/dawn/hello_triangle.zig

Updates `gpu-dawn` to the latest upstream Dawn version.
https://github.com/hexops/dawn now has an even better generation strategy now, too:
* `upstream` branch tracks the dawn.googlesource.com upstream repo.
* `main` branch is `upstream` with our `mach/` generation scripts, and sometimes temporary patches we're upstreaming.
* `generated-2022-02-17` contains the result of updating `upstream` and `main`, then forking `main` and comitting the Dawn dependencies and generated code.
This makes updating Dawn easier, and by using separate `generated-<date>` branches we always get a clean history: we can trim down Dawn further, etc. to reduce the size. And we can more easily compare our changes against upstream and past generated branches.
`gpu-dawn` then targets a `generated-<date>` branch, and …

gpu-dawn: update Dawn to latest generated-2022-02-17

---

gpu-dawn/build.zig
gpu-dawn/src/dawn/hello_triangle.zig
gpu-dawn/src/dawn/sample_utils.zig

Helps #86
(this is still not the complete set of patches needed for gpu-dawn to build on Windows)

gpu-dawn: various windows support improvements

---

glfw/src/main.zig
glfw/src/native.zig
gpu-dawn/build.zig
gpu-dawn/src/dawn/dawn_native_mach.cpp
gpu-dawn/src/dawn/dawn_native_mach.h
gpu-dawn/src/dawn/hello_triangle.zig
gpu-dawn/src/dawn/sample_utils.zig

i.e. everywhere except OpenGL backends, as Dawn does not yet support the WGPUSurface API for OpenGL backends.
Fixes #121

gpu-dawn: update example, use newer WGPUSurface API where available

---

glfw/src/hat.zig
glfw/src/mod.zig

Not sure why we had these here, but alignment on a packed struct seems somewhat
nonsensical (after all, it's fields are packed as closely together as possible
so what would alignment refer to?) removing seems fine and fixes compilation with
latest Zig:
```
/Users/slimsag/Desktop/hexops/mach/gpu-dawn/libs/mach-glfw/src/hat.zig:8:20: error: unable to override alignment of packed struct fields
up: bool align(@alignOf(u8)) = false,
^
/Users/slimsag/Desktop/hexops/mach/gpu-dawn/libs/mach-glfw/src/mod.zig:10:23: error: unable to override alignment of packed struct fields
shift: bool align(@alignOf(c_int)) = false,
^
```

glfw: remove alignment from packed structs / fix compilation with latest Zig

---

ecs/src/entities.zig
ecs/src/main.zig
ecs/src/systems.zig

In the past:
* hexops/mach#156 was the initial ECS implementation detailed in https://devlog.hexops.com/2022/lets-build-ecs-part-1
* hexops/mach#157 was the second major redesign in which we:
* Eliminated major limitations (e.g. inability to add/remove components at runtime)
* Investigated sparse sets
* Began thinking in terms of databases
* Enabled runtime introspection
Our second revision of the ECS, however, still had _archetypes_ exposed as a public-facing user concern. When a new component was added to an entity, say a weapon, the table storing entities of that archetype changed to effectively have a new column `?Weapon` with a null value for _all existing entities of that archetype_. We can say that our ECS had archetypes as a user-facing concern AND this made performance worse: …

ecs: third major redesign/rethink of implementation

---

gpu-dawn/build.zig

This allows gpu-dawn to be vendored into a project when building from source.

gpu-dawn: build.zig needs to reference thisDir for C file

---

.github/workflows/ci.yml
.github/workflows/m1_ci.yml
build.zig
examples/frag.wgsl
examples/main.zig
examples/vert.wgsl
glfw/build.zig
gpu/build.zig
src/c.zig
src/main.zig
src/util.zig

This makes the top-level `mach` package our higher-level app package. For today, this is a much nicer way to get introduced to WebGPU: `examples/main.zig` is only 114 LOC - while `gpu/examples/main.zig` is 481 LOC (mostly setup logic!)
In the future, this package is also where we will bridge other platforms - such as iOS, Android, and Browser all together.
Fixes hexops/mach#190

add higher-level app package

---

build.zig
glfw/build.zig
gpu/build.zig

There are a few changes in one PR here:
- Add explicit `std.build.Pkg` types to `pkg` variables in `build.zig`s
- Publicize `gpu` and `glfw` from the toplevel `build.zig` to make it easier to use those from projects importing that
- Run `zig fmt` on the toplevel build.zig (one tiny whitespace change)
---

Tweak build.zigs to make using app library slightly easier

---

glfw/build.zig
gpu-dawn/build.zig

Every library we want to link against is either provided by the Zig
toolchain or part of our SDK. Therefore, using pkg-config to link
against libraries on the host system is never what we intend.
To fix this, use linkSystemLibraryName() everywhere instead of
linkSystemLibrary() as the latter integrates with pkg-config while the
former just passes -lfoo to the zig compiler.
In combination with Zig commit 38d6e1d8a8 fixing an std.build bug,
this change fixes the linking of the necessary X11 libraries on my
x86_64 glibc based Void Linux system.

build: never use pkg-config to link system libraries

---

gpu/src/Buffer.zig
gpu/src/Device.zig

+ same for getConstMappedRange
+ mirror align fix for getConstMappedRange
rationale:
user needs to align buffer on creation, as in
gpu.Buffer.Descriptor{ .size = size, ... }
so `size == sizeOf(T) * len` might not always hold true.
on `getMappedRange` request, there is no way to specify
that size was manually aligned, and using the function directly
with realigned size gives extremely unhelpful error:
thread 254201 panic: attempt to use null value
.../mach/gpu/src/NativeInstance.zig:1721:42: 0x480747
in .gpu.NativeInstance.buffer_vtable.getMappedRange (game)
return @ptrCast([*c]u8, range.?)[0..size];
^
it seems, requested size must match size specified on creation exactly.
so this commit does exactly that. aligns buffer size to 4 - something
that user must have done already if this point …

fix getMappedRange size alignment

---

glfw/src/errors.zig

First step towards https://matrix.to/#/!bIJeTLtOHucXQpqIcH:matrix.org/$1ycSFVJ77wBmUJCPF_o8I7aXmN7vqc3rTXHpsFjdKV0?via=matrix.org&via=mozilla.org&via=one.ems.host
(Getting error description set by glfw in tests)
The API to access the error message was absent in the first place. This PR however adds it in a way that it would be convenient to work with (and hence its not completely identical to C version.
This does not actually modify the tests yet, I m planning to do that with another PR.

glfw: add getErrorString() to access the current error description

---

src/main.zig

This uses glfw.setErrorCallback to set a global callback in mach's App which would work across all mach applications
How would this behave?
- The callback would show the error message first and then the regular behavior will follow: app would shutdown with an error trace

mach: set error message to be shown on glfw error

---

.gitmodules
gpu-dawn/.gitmodules

Updates Dawn to latest revision as of 2022-04-17 https://github.com/hexops/dawn/commit/69daaab75938cbe10c40f1a04988d46e09c3007d
* Followed https://github.com/hexops/dawn/tree/main/mach#updating
* Includes a fix for UB issue https://github.com/hexops/dawn/pull/9 (I will send a CL for this upstream soon.)
* Verified examples run on macOS (other OSes will get built by CI and verified later)
Closes hexops/mach#221

gpu-dawn: update Dawn to latest revision as of 2022-04-17

---

.gitmodules
gpu-dawn/.gitmodules
gpu-dawn/build.zig

Effectively a redo of hexops/mach#231 where I messed up the submodule update by accident.
Updates Dawn to latest revision as of 2022-04-18 https://github.com/hexops/dawn/commit/c7b7b6def672299ea3094161a83b22e19ed409ff
* Followed https://github.com/hexops/dawn/tree/main/mach#updating
* The UB issue should now actually get fixed (once CI builds the binary releases.)
* Verified example runs on macOS.
Helps hexops/mach#221

gpu-dawn: update Dawn to latest revision as of 2022-04-18

---

gpu/src/Device.zig
gpu/src/NativeInstance.zig
gpu/src/Queue.zig
gpu/src/Texture.zig

There were some changes in `webgpu.h` -- changes in this PR are required for "release-51a7db1" binaries and when using `-Ddawn-from-source=true`.

gpu: Changes needed for latest Dawn (generated-2022-04-18).

---

examples/triangle/main.zig

current `Blend` does actually blend colors (which includes background color), which might surprise people trying to modify example. the fix introduces `Blend` that actually writes over previous color.

examples: fix blend mode in triangle example

---

.github/workflows/m1_ci.yml
glfw/.github/workflows/m1_ci.yml
gpu-dawn/.github/workflows/m1_ci.yml

The workflow uses a self hosted runner which is only available for hexops/mach* repositories. Without this commit, whenever a fork of mach or mach-* were pushed, it would queue an aarch64-mac job and then crash after one day due to no machines being found.

CI: dont run aarch64-mac workflow on forks

---

.gitmodules
gpu-dawn/.gitmodules

upstream @ c2f9fea56bee11cf573fe90b08a296a38202500b
Includes fix for UB on Linux/Vulkan: https://github.com/hexops/dawn/pull/11
Closes hexops/mach#239

gpu-dawn: update Dawn to latest revision as of 2022-04-21

---

src/main.zig

Choose first `vulkan` adapter, instead of last.
Fixes picking `llvmpipe` software only implementation, while accelerated one is available.
Note: fix might be not perfect, as it relies on order of adapters instead of checking the properties.

mach: choose first vulkan adapter

---

build.zig

Without this change, anytime a dependency is modified, all the examples and applications are rebuilt before tring to run any of them. The problem with this approach is that it leads to long compile times which will keep on increasing as more and more examples are added.
The old behavior is still preserved with a new step ``compile-all``. In future this could be added to CI just to check if all the examples and applications at least build properly. This is not being done right now because zig std lib is undergoing lots of breaking changes right now and it will keep failing CI.
---

build: compile examples and applications on demand

---

.github/workflows/ci.yml
.github/workflows/m1_ci.yml

From https://github.com/hexops/mach/pull/259#issuecomment-1113944683
Updates CI to run step ``zig build compile-all`` which compiles all the examples and applications to check if all are at least building properly.
Not added to x86_64-macos because it just fails early with some other error and macos doesnt even have tests enabled, maybe for the same reason?
---

CI: check compilation of all examples

---

examples/fractal-cube/main.zig
examples/instanced-cube/main.zig
examples/rotating-cube/main.zig
examples/textured-cube/main.zig
examples/two-cubes/main.zig
src/Engine.zig
src/Timer.zig
src/main.zig
src/native.zig

This Timer uses std.time.Timer as backing timer in native platforms, and will use custom timers for special platforms (wasm, android?, ios?).
Unlike std.time.Timer, its primary API is focused on floats. Also meant to provides some convenient functions alongside base ones.
Follows std.time.Timer API, but methods by default return f32 i.e non-precise variant with precise variants available returning u64.

mach: introduce cross platform Timer abstraction

---

examples/advanced-gen-texture-light/main.zig
examples/fractal-cube/main.zig
examples/gkurve/main.zig
examples/instanced-cube/main.zig
examples/rotating-cube/main.zig
examples/textured-cube/main.zig
examples/two-cubes/main.zig
src/Engine.zig
src/enums.zig
src/native.zig
src/structs.zig

Relevent commit message:
```
This commit changes the former callback based design to handle key input
(GLFW-like) to an event loop based design (SDL-like). This uses a
TailQueue to store the events from inside of standard glfw callbacks.
This Queue is then popped while polling, thereby emulating event loop.
Removes from Engine the function: ``setKeyCallback`` and adds the
function: ``pollEvent`` which may return an event or null.
This change was done for two reasons:
1) Removing dependence of Engine on App. This was a circular dependency
and a genuine bad design.
2) Solve the recent regression due to the same which was (i) preventing
using types declared in Engine.zig and (ii) preventing usage of
multiple source files in an application.
Currently only key press and release events are …
```

mach: Event loop based input handling

---

examples/boids/main.zig

std.debug.print uses IO which depends on file system and thus needs
support from OS, which dont have in freestanding targets (like WASM).
---

examples: boids: use std.log.info instead of std.debug.print

---

build.zig
gpu/build.zig
src/Engine.zig
src/Timer.zig
src/mach.js
src/wasm.zig
www/template.html

This is very incomplete, it is not ready to support the examples yet.
This PR just implements the barebones structures needed for future wasm development. The build system support is also lacking, which will be done progressively.
In order to run:
```sh-session 
zig build compile-all -Dtarget=wasm32-freestanding-none 
cd zig-out/lib
cp ../../www/template.html application.html
cp ../../src/mach.js .
python3 -m http.server
```
This PR also implements some general build.zig sdk improvements:
```
- Target is now passed as an option in App.init()
- Always install() in all case
- Add functions getInstallStep(), setBuildMode() and run()
```

mach: initial wasm platform implementation

---

build.zig

Discussion: https://matrix.to/#/!hPlvgnLQhMkTucKPrh:matrix.org/$P_aED8yOzDymRmMF6aT0ez19GMgSY8ci9jnNAq8eRJo?via=matrix.org
Commit message:
```
These steps will only compile and install the applications but not run
it. To be used as ``zig build example-*`` and ``zig build shaderexp``
respectively, i.e without the run prefix.
```
Also made a minor change to include the name of example in their respective compile and run steps.
---

mach: add compile-only step for examples and shaderexp

---

.gitmodules
build.zig
tools/html-generator.zig
tools/http-server.zig
www/template.html

- Made general improvements to build system on how to add dependencies, removed redundant dependencies internally
- In case of wasm, install the necessary js and html files in prefix/www. The main HTML file is generated with an application placed in tools/html-generator.zig. This application would prove to be more useful in future when we have more modules inside the engine (as all js files need to be listen inside this HTML file)
- In case of wasm, serve the application using a http server placed in tools/http-server.zig. The address and port can be customized using the environment variables ``MACH_ADDRESS`` and ``MACH_PORT`` respectively.
- Finally in case of wasm, launch a web browser with the link where the application is being served.
The serve + launch steps can be customized with …

Mach: improvements to build system (for wasm)

---

gpu/src/Queue.zig

gpu: Queue.WorkDoneStatus fields should be snake_case.

---

.github/workflows/ci.yml
.github/workflows/m1_ci.yml
build.zig

Also added compile-all step to CI so that these dont happen in future.
Currently CI is failing because zig version on it has not been updated yet
---

mach: build: disable gkurve example of wasm as freetype cant be compiled for

---

freetype/examples/single-glyph.zig
freetype/src/freetype/image.zig

For some characters (eg \r) the returned glyph will have .{.rows = 0, .width=0, .pitch = 0, .buffer = null}. In zig null[0..0] causes a panic rather than returning an empty slice.

freetype: Avoid dereferencing null bitmap buffer.

---

ecs/build.zig
ecs/src/entities.zig

This switches our ECS over to manually managed memory (one `[]u8` per archetype table, with multiple column arrays packed into it - dealing with padding/alignment ourselves) rather than the prior 1 `ArrayList(Component)` per component in an archetype table.
There is no change in the user-facing API yet, the goal of this change is just to get to manually managed memory. There are some things that are not entirely optimal because of this that I will explore in future PRs.
This idea was discussed in depth in [#ecs:matrix.org](https://matrix.to/#/#ecs:matrix.org) (thanks Levy!) Notable advantages from my POV:
1. This means we don't need an `ErasedComponentStorage` interface, which is nice.
2. It means component storage does not have to have a Zig type. It could e.g. in theory enable the ECS …

 ecs: switch from ArrayList per-table-per-component-set -> single-[]u8-per-table

---

glfw/src/Window.zig
src/platform/mach.js
src/platform/native.zig
src/platform/wasm.zig
src/structs.zig
www/template.html

Adds a new field to mach.Options called ``fullscreen: bool = false``. This PR implements fullscreen support for native and wasm platforms. 
For native, glfw doesn't supports getting the currently active monitor (i.e monitor having input focus), so the fullscreen window opens up on primary window by design.
For wasm, fullscreen support is primarily implemented with styles because html fullscreen support is broken in many ways. With fullscreen support, the border around canvas is also slightly broken when you switch between windows and fullscreen modes but thats a problem only for as long as we dont have rendering support for wasm.
---

mach: Implement fullscreen application support

---

ecs/src/entities.zig

Closes #341 and fixes two other bugs: 
- a bug with the alignment calculation in `setCapacity()` which arose when the initial offset has the correct alignment, leading to the padding equal to the column element size (as oppose to 0 padding)
- an off-by-one error in `appendUndefined()`.

ecs: fixes for `setCapacity()` and `appendUndefined()`

---

glfw/.gitmodules

I've been using the mach-glfw sub(cloned)-repo and the recent submodule path change from https://github.com/hexops/mach/pull/346 doesn't match up with what mach-glfw expects as a standalone repo. This should be reproducible with the example vulkan triangle repo: https://github.com/hexops/mach-glfw-vulkan-example.

glfw: submodule path fix for subrepo

---

glfw/src/vulkan.zig

Fixed an issue in the GLFW bindings where `getPhysicalDevicePresentationSupport` in `vulkan.zig` would segfault due to dereferencing an opaque handle. Note that I'm using https://github.com/Snektron/vulkan-zig. It might be better to use anytype and check if it's an enum or not like done in `createWindowSurface`:
https://github.com/hexops/mach/blob/fa5afee5bce4be815d7a69926bcdec54d26a4889/glfw/src/vulkan.zig#L246-L251

Fixed segfault in `getPhysicalDevicePresentationSupport`

---

gpu/src/NativeInstance.zig
gpu/src/Queue.zig

This change removes a footgun where the queue used to submit with a callback must be valid when the callback is run.  This change makes it clear (hopefully) to the user that the queue does not need to be valid, only the `WorkDoneCallback` does, when the callback gets run.
Helps hexops/mach#183

Store pointer to WorkDoneCallback in gpu.Queue

---

src/platform/native.zig
src/platform/wasm.zig

This PR makes `src/platform/native.zig` re-export logging declarations from the `"app"` package. As mentioned in #360, these are the magical declarations `std` uses that I think should clearly be re-exported.
I'm not sure at the moment to handle a custom `log` function for wasm as I haven't used it, so this PR only deals with the native target.

Use `log_level` and `scope_levels` pub decls from App

---

src/Engine.zig
src/platform/native.zig

Fixes #367 
This only makes changes to native because wasm doen't need any changes here.

mach: Use math.inf instead of math.floatMax for indefinite wait of events

---

src/platform/mach.js
src/platform/native.zig
src/platform/wasm.zig
src/structs.zig

This adds some additional events. It also does some busywork tracking cursor position and key modifiers and attaches copies of that state to events.
I don't see any tests for mach platform but `zig build compile-all` works and keypresses still work in `zig build run-example-advanced-gen-texture-light`

mach: flesh out mach.Event

---

ecs/src/entities.zig
src/platform/native.zig

The `swapped_entity_id` was getting the id of the row _before_ the swap remove. This meant the position of the swapped entity was not updated in the `EntityID` -> `Pointer` hash map.

{ecs,mach}: fix some memory issues

---

examples/advanced-gen-texture-light/main.zig
examples/boids/main.zig
examples/fractal-cube/main.zig
examples/gkurve/main.zig
examples/instanced-cube/main.zig
examples/rotating-cube/main.zig
examples/textured-cube/main.zig
examples/triangle/main.zig
examples/two-cubes/main.zig
shaderexp/main.zig
src/Core.zig
src/main.zig
src/platform/common.zig
src/platform/native.zig
src/platform/wasm.zig
src/structs.zig

This PR renames `mach.Engine` -> `mach.Core`, and prepares to make _ECS_ the "Engine"
This originates from https://github.com/hexops/mach/pull/349, the TL;DR is that there are two types of Mach apps:
* **Mach core**: "I want a window, input, and WebGPU graphics that work on any OS - that's it."
* **Mach engine**: Higher-level APIs built on top of _Mach core_, using ECS. Everything not in core is implemented and connected via ECS patterns, and hence ECS is literally _the engine_ - it's what ties everything together!

The great rename: Engine->Core

---

examples/advanced-gen-texture-light/main.zig
examples/boids/main.zig
examples/fractal-cube/main.zig
examples/instanced-cube/main.zig
examples/rotating-cube/main.zig
examples/textured-cube/main.zig
examples/triangle/main.zig
examples/two-cubes/main.zig
shaderexp/main.zig
src/platform/common.zig
src/platform/native.zig
src/platform/wasm.zig

This requires apps expose a `pub const App` from their `main.zig`, effectively adopting the high-level/low-level application API outlined in https://github.com/hexops/mach/pull/349
If `pub const App` does not exist, a clear compiler error is produced:
```
./src/platform/common.zig:5:9: error: expected e.g. `pub const App = mach.App(modules, init)' (App definition missing in your main Zig file)
@CompileError("expected e.g. `pub const App = mach.App(modules, init)' (App definition missing in your main Zig file)");
^
./src/platform/native.zig:13:28: note: called from here
common.checkApplication(app_pkg);
^
./src/platform/native.zig:12:10: note: called from here
comptime {
^
./src/platform/native.zig:15:20: error: container '.app' has no member called 'App'
const App = app_pkg.App;
^
```

mach: require a 'pub const App' to be exposed

---

build.zig
js-runtime/.gitignore
js-runtime/LICENSE
js-runtime/LICENSE-APACHE
js-runtime/LICENSE-MIT
js-runtime/README.md
js-runtime/build.zig
js-runtime/src/js-runtime.js
js-runtime/src/main.zig
www/template.html

Upstreams js-runtime from https://github.com/iddev5/zig-js-runtime. This module should be considered experimental and its API is not final. It is inspired from Go's syscall/js module. It is not a reimplementation, but rather an independent implementation.
There is also a workaround for a limitation right now. The html-generator has no way to dynamically add JS sources (and that can't be done without using a preprocessor library) so we hardcode js-runtime in it.
In the future, I think the correct behavior would be to move tools/ inside js-runtime along with a wasm application building SDK and get rid of any direct JS access we have today (which is just src/platform/wasm.zig and src/platform/mach.js).
---

js-runtime: add/upstream new js-runtime library inspired by Go's syscall/js package

---

glfw/src/Window.zig

While attempting to run the mach examples on WSLg, I ran into an issue using the OpenGL backend:
```
thread 11857 panic: attempt to cast negative value to unsigned integer
/home/jane/mach/glfw/src/Window.zig:581:22 0x4af643 in Platform.init (example-boids)
return Pos{ .x = @intCast(u32, x), .y = @intCast(u32, y) };
^
```
the simplest solution, to use a signed integer instead of an unsigned one, worked perfectly fine to resolve this issue and the example built and ran without issue afterwards.
---

glfw: respect negative coordinates in window

---

js-runtime/src/js-runtime.js
js-runtime/src/main.zig

Adds the following new functions: 
- ``js.Value.eql``
- ``js.Value,instanceOf``
- ``js.Value.format`` to be used with stdlib formatting
- ``js.Object.attributeCount``
- ``js.Function.paramCount`` (note: doesn't works for native functions, yet)
---

js-runtime: More functional improvements

---

glfw/src/Window.zig
src/platform/native.zig

This regression was introduced with https://github.com/hexops/mach/commit/04013379db7fe2d1d33e54792647c933435bb30f and also partially reverts https://github.com/hexops/mach/commit/d3feaed383f9a7f8f8d5fa4d9e1d496ea7fbebc5
Instead of doing the intCast, the other way to solve the problem is this suggestion: https://github.com/hexops/mach/pull/393#issuecomment-1178655298 (which is to use i32 for pos instead of i64), if it is an accepted solution.
---

{mach, glfw}: Fix broken build due to using u32 inplace of i32

---

ecs/src/entities.zig

The reference to the old archetype is invalidated by getOrPut() calls of
std.ArrayHashMap. The implementation of std.ArrayHashMap means that
pointers can be invalidated on getOrPut() calls _even if the key exists
in the map_. This means that the reference to the old archetype needs to
be refreshed unconditionally (i.e. not only if the new archetype didn't
exist previously).
Maybe it's worth suggesting upstream that `std.ArrayHashMap` changes so `getOrPut()` doesn't invalidate pointers if the key exists. The issue is that `getOrPut()` calls `ensureTotalCapacity()` to make sure there is a free element, thus invalidating pointers if the map is full.

ecs: fix pointer invalidation in get/setComponent

---

build.zig
libmach/.gitignore
libmach/Makefile
libmach/README.md
libmach/test.c
libmach/test.lisp
src/bindings.zig
src/platform/libmach.zig

This pull request includes:
1. C API bindings for Core Mach, exported from `src/bindings.zig`
2. Changes to `build.zig` in order to build `libmach`
3. Test programs located in `libmach/` to check if `libmach` works as expected

libmach: initial API bindings for mach core

---

sysaudio/src/webaudio.zig
sysjs/src/mach-sysjs.js
sysjs/src/main.zig

Read individual commit messages for more info
The audio playback implementation itself is quite standard, and processing is done on per sample basis. Currently sample format in data callback is hard coded to f32. Even though WebAudio doesn't supports any other format, it should be a []u8 (probably) so that use can bit cast it as per they want. 
The callback itself along with user_data are stored on JS side. JS can technically store opaque pointers, but we dont have any custom function to handle it yet, so just cast to and fro f64, it should be cleaned up someday.

{sysaudio,sysjs}: Implement playback with data_callback

---

freetype/src/freetype/Face.zig
freetype/src/harfbuzz/main.zig
freetype/test/main.zig

The harfbuzz tests randomly failed to compile with stage2. With the usual fix it doesn't fail anymore, but I wonder how it managed to compile before, and since the behaviour is random there must be some UB in the compiler regarding this. Should I write about this in the stage2 issue?
Also `Face.getGlyphName()` returned a slice from a buffer on the Stack. I decided to pass the slice to the function, so that memory management of the buffer is left to the user, though this means that the user still has to call `sliceTo()` on his buffer to get the actual string.

freetype: fix tests for stage2 and Face.getGlyphName()

---

build.zig
libmach/test.c
libmach/test.lisp
src/platform/libmach.zig
src/platform/native.zig

This PR makes a few changes to the libmach API in accordance with the comments on the previous PR.
Also, it seems like I forgot to stage my changes to `build.zig` in the previous commit, so they are included in this commit instead.

libmach: update API again, factors out init/update/deinit from native

---

freetype/examples/glyph-to-svg.zig
freetype/examples/single-glyph.zig
freetype/src/c.zig
freetype/src/freetype/GlyphSlot.zig
freetype/src/freetype/computations.zig
freetype/src/freetype/freetype.zig
freetype/src/freetype/image.zig

i'd skipped `FT_Sin`, `FT_Cos`, etc. because zig's stdlib already contains those functions

freetype: Support API Coverage++

---

glfw/build.zig

This adds the `shared` option, which builds GLFW into it's own shared library. 
The use case for this is as follows (in this setup, the exe loads the game dll at runtime using std.DynLib):
```
// Engine launcher
const exe = b.addExecutable("ion", "src/main.zig");
{
... setup the exe build step ...
exe.addPackage(glfw.pkg);
glfw.link(b, exe, .{
.shared = true
});
}
// Game dll
const game = b.addSharedLibrary("game", "game/src/game.zig", .unversioned);
{
... setup the game build step ...
game.addPackage(glfw.pkg);
glfw.link(b, game, .{
.shared = true
});
}
```
This way, both `game` and `exe` link with the shared library, so that there is one copy of the `_glfw` global state in the process. Static linking wouldn't work here, as the dll and exe would have separate copies of `_glfw`.
A couple …

glfw: add shared option which builds glfw into it's own shared library

---

build.zig

Forgot to use `thisDir() ++ "/gamemode/gamemode.zig` in build.zig

gamemode: Fix gamemode package path in build.zig

---

.github/workflows/ci.yml
.github/workflows/m1_ci.yml
build.zig

Fixes #448 
gpu-dawn testStep has been removed in https://github.com/hexops/mach/commit/fbfd2f336b33019bb4d5d5c5a4fea56183cb8c3d but you forgot to remove it from `build.zig`

CI: remove unneeded builds on sub-projects

---

shaderexp/main.zig
shaderexp/vert.wgsl

Using a fullscreen triangle is (very) marginally better than a quad because it avoids overdraw and isn't any more complicated. Moving the static vertex data for the fullscreen primitive into the shader simplifies command buffer recording and pipeline layout.

shaderexp: Use fullscreen triangle instead of quad, move vertex data into the shader

---

build.zig

This commit fixes a bug where the build script would look for
an assets directory that has been moved.

examples: fix old example assets directory paths

---

libs/gpu-dawn/sdk.zig

This fixes an incorrectly capitalized library path for `DirectXShaderCompiler`, which makes the dawn build fail on linux.

gpu-dawn:build: fix incorrect capitalization

---

build.zig
examples/sysaudio/main.zig
libs/sysaudio/build.zig
libs/sysaudio/soundio/InStream.zig
libs/sysaudio/soundio/OutStream.zig
libs/sysaudio/src/main.zig
libs/sysaudio/src/soundio.zig
libs/sysaudio/src/webaudio.zig
libs/sysjs/src/mach-sysjs.js
libs/sysjs/src/main.zig
src/main.zig
src/platform/wasm.zig

After this PR, `sysaudio` works enough to run a virtual piano example in both WASM and natively:
```
zig build run-example-sysaudio -Dtarget=wasm32-freestanding-musl
```
```
zig build run-example-sysaudio
```
I uploaded the WASM example really quick to http://slimsag.com/mach/piano/ but this link probably won't stay valid for long (it will move to machengine.org later, but it needs a proper GUI.)
Simply click on the window / border area, and then type on your keyboard. It assumes QWERTY keyboard layout for now.

all: add sysaudio example

---

libs/freetype/src/Face.zig

Face.availableSizes previously only returned the first available size - this just makes it return a slice as you'd expect.

freetype: correct return type of Face.availableSizes

---

examples/sysaudio/main.zig
libs/sysaudio/src/main.zig
libs/sysaudio/src/soundio.zig
libs/sysaudio/src/webaudio.zig

This started with the sysaudio example running, but not showing up on my screen. @leroycep gave me a patch that made it show up by clearing the screen. 
My system is using pipewire running at a sample rate of 48000 hertz, so I was getting a lot of clicking from buffer underruns. I haven't yet fixed that because I got distracted by separating the configuration from the descriptor.

{sysaudio,examples}: get sysaudio running on linux, separate audio configuration and descriptor

---

examples/sysaudio/main.zig
libs/sysaudio/src/main.zig
libs/sysaudio/src/soundio.zig
libs/sysaudio/src/webaudio.zig
src/platform/wasm.zig

Fix compile errors for web, and moves the Device and Properties declarations into the backend files.

sysaudio: fix compile for web

---

libs/ecs/src/entities.zig
libs/glfw/src/Joystick.zig
libs/sysaudio/src/soundio.zig
src/platform/native.zig

Lastest Zig complains about this, so I must remove it to compile examples.

all: remove ineffective `_ = variable` assignments

---

libs/glfw/src/cimport/c_darwin_native.zig

Hello! This little PR should fix once for all the pointless discards errors on `mach-glfw`.

glfw: remove ineffective `_ = variable` assignment

---

libs/glfw/build.zig

Discussed in the help channel, will spit `lld` warnings:
```
ld.lld: warning: /home/arias/dev/mach/zig-cache/mach/gpu-dawn/release-777728f/x86_64-linux-gnu/release-fast/libdawn.a: archive member '/home/runner/work/mach-gpu-dawn/mach-gpu-dawn/zig-cache/o/e3b9895e4258fa9e9d779c73d05e739a/libglfw.a' is neither ET_REL nor LLVM bitcode
ld.lld: warning: /home/arias/dev/mach/zig-cache/mach/gpu-dawn/release-777728f/x86_64-linux-gnu/release-fast/libdawn.a: archive member '/home/runner/work/mach-gpu-dawn/mach-gpu-dawn/zig-cache/o/e3b9895e4258fa9e9d779c73d05e739a/libglfw.a' is neither ET_REL nor LLVM bitcode
ld.lld: warning: /home/arias/dev/mach/zig-cache/mach/gpu-dawn/release-777728f/x86_64-linux-gnu/release-fast/libdawn.a: archive member '/home/runner/.local/share/hexops/sdk-linux-x86_64/root/usr/l …
```

glfw: fix implicit function declaration error on clang15

---

examples/advanced-gen-texture-light/main.zig
examples/cubemap/main.zig
examples/fractal-cube/main.zig
examples/gkurve/main.zig
examples/image-blur/main.zig
examples/instanced-cube/main.zig
examples/rotating-cube/main.zig
examples/textured-cube/main.zig
examples/two-cubes/main.zig
shaderexp/main.zig
src/structs.zig

set a saner default and moved the comment about zero window size on linux to the options struct.

{mach,examples,shaderexp}: fix default minimum window size

---

build.zig
examples/ecs-app/main.zig
examples/gkurve/main.zig
src/Core.zig

some pointless discards, a typo, and adding gamemode to libmach because it was preventing a compile-all on linux.

all: fix pointless discards; typo; fix libmach compilation on Linux

---

src/platform/common.zig

Stage2 Zig ends up coercing structs without any fields into consts. The current error given is not entirely clear to the cause or how to fix the issue for users.

mach: better compile error for missing fields in App.

---

src/platform/native.zig

Noops swapchain creation for when the target_desc has a width or height of 0. Cases that hit this are when a user minimizes a window or resizes the window to only render the toolbar.
Helps https://github.com/hexops/mach/issues/528

mach: 0 size swapchain noop fix

---

libs/freetype/src/harfbuzz/buffer.zig

There's an undocumented private field in this struct which wasn't replicated, meaning getGlyphPositions was returning garbage data.

freetype/harfbuzz: correct Position struct layout

---

libs/freetype/src/main.zig

This declaration itself was nonsensical, as the file being imported was from the harfbuzz package (instead users should import the harfbuzz package directly). But as well as being nonsensical, this line was occasionally triggering a stage2 bug which we haven't quite tracked down yet which seems to be something to do with conflicting modules importing a file. This issue meant that projects with a specific dependency pattern on freetype and harfbuzz would sometimes randomly get a nonsensical compilation error. This change works around that issue for mach-freetype.

freetype: don't expose harfbuzz directly from freetype pkg

---

libs/glfw/system_sdk.zig

Breaking zig change for some error handling.
See https://github.com/Vexu/zig/commit/0b1dd845d9ac15ade5748dcb6ffa6b868fdfe0c0

glfw: fix compilation with latest zig master

---

libs/glfw/.gitignore
libs/glfw/src/native.zig

Should close #582 (unless there is something wrong on darwin)
Commits e7e179f6 72ddde25 removed a cImport workaround in glfw, but it looks like it removal of the generation of `libs/glfw/src/c_native.zig` wasn't taken into account (likely because this file is in the `.gitignore`). I seem to be able to fix this by importing `cimport/c_normal_native.zig` instead of `c_native.zig` in `src/native.zig` but, I have no idea if this is meant to work for darwin or not, but hopefully CI will say it does (this change should fix CI failing  the glfw-test)

glfw: fix native import

---

dev/ensure-standard-files.zig
libs/gpu-dawn/.github/workflows/publish_release.yml
libs/gpu-dawn/.gitignore
libs/gpu-dawn/sdk.zig

This is a much simpler solution for solving the primary problem I am concerned about in https://github.com/hexops/mach/pull/584 (the more I thought about that solution, [the less I liked it](https://twitter.com/slimsag/status/1581645393770577920)). This new approach:
1. We continue using a few submodules (at least in the Mach codebase.)
2. `dawn` and `DirectXShaderCompiler` (the only two unwiedly submodules that are not needed by default since we download binary builds) are kicked out of the tree.
3. If you specify `-Ddawn-from-source=true`, `zig build` handles cloning those dependencies for you (using `git clone`, not as submodules.)

gpu-dawn: kick large submodules out of tree

---

dev/ensure-standard-files.zig
libs/trimesh2d/.gitattributes
libs/trimesh2d/.github/FUNDING.yml
libs/trimesh2d/.github/pull_request_template.md
libs/trimesh2d/.github/workflows/ci.yml
libs/trimesh2d/.gitignore
libs/trimesh2d/LICENSE
libs/trimesh2d/LICENSE-APACHE
libs/trimesh2d/LICENSE-MIT
libs/trimesh2d/README.md
libs/trimesh2d/build.zig
libs/trimesh2d/src/main.zig

This adds a tesselator used for text rendering in my SYCL 2022 talk ("gkurve: simpler vector graphics")
I think this is not the right long-term polygon tesselator to have, but it'll do for now.

trimesh2d: add tesselator used for text rendering in SYCL 2022 talk

---

build.zig
libs/model3d/build.zig

This allows the library to link with projects that are using different c compiler options (E.g compiling C++ or using a different c standard)
Also adds .use_model3d option to mach build system. If set to true, model3d will be linked in statically to target project.

{mach,model3d}: link model3d as static lib instead of adding C files to build step

---

src/platform/native.zig
src/structs.zig

For multiple monitors (at least on native), it would be nice to be able to select the monitor for fullscreen mode.

mach: add option to set the monitor index on fullscreen

---

libs/model3d/build.zig

This is required for building with a non-native target, otherwise library is build for the native platform and attempts to link fail

model3d: set cross-target when compiling statically

---

libs/sysaudio/sdk.zig

Do not really know if it's ok or not, but for now, it is the only way to build Mach under macOS 13 without preparing actual SDK (which is a hard task for me). With this change, one can pass overridden `sdk_list` to glfw and sysaudio libs.
Btw on my laptop it is enough to copy `Sdk` from 12th version and just change semver to 13 to successfully compile Mach.
Can be used as a temporary workaround for https://github.com/hexops/mach/issues/610

sysaudio: add ability to provide system_sdk options

---

libs/freetype/README.md
libs/freetype/build.zig

I ran into this when trying to use both mach-freetype and zig-libcurl (https://github.com/mattnite/zig-libcurl).  First I got undefined symbols like:
```
ld.lld: error: undefined symbol: inflate
>>> referenced by content_encoding.c:196 (libs/zig-libcurl/curl/lib/content_encoding.c:196)
>>>               /home/dvanderson/gui/zig-cache/o/e7a848841ad0f6ef64dd93429b6b18b5/content_encoding.o:(inflate_stream) in archive /home/dvanderson/gui/zig-cache/o/95294db893708419c83e8414f31f1147/libcurl.a
```
So I added zig-zlib (https://github.com/mattnite/zig-zlib).  Then I got duplicate symbols like:
```
ld.lld: error: duplicate symbol: inflateResetKeep
>>> defined at inflate.c:123 (libs/mach/libs/freetype/upstream/freetype/src/gzip/inflate.c:123)
>>> …
```

freetype: add option to build using separate zlib

---

libs/ecs/src/entities.zig

fixed segfault when calling deinit on empty world by setting a default value to archetype blocks, rather than them being undefined
fixes #627

ecs: fix segfault in Entities.deinit()

---

libs/freetype/src/main.zig

Fixes the following error when running the freetype tests.
`libs/freetype/src/main.zig:37:46: error: unable to open 'libs/freetype/src/../upstream/assets/FiraSans-Regular.ttf': FileNotFound`
Not entirely sure what is going on here. I would have expected the path to be `'src/../upstream/assets/FiraSans-Regular.ttf'` based on the sdkPath function but either way I don't think the sdkPath wrapper is needed here.
This works for running all the mach tests, and only the freetype tests from mach/libs/freetype

freetype: incorrect font path in embedFile

---

libs/gpu/README.md
src/platform/util.zig

Sorry, it was not caught by tests, only by `mach-examples`
Signed-off-by: Eric Joldasov <bratishkaerik@getgoogleoff.me>

{mach,gpu}: more undef/nul -> undefined/null renames

---

src/platform/util.zig

I made a change in order to fix the compilation (at least on m1 macs) with latest zig (0.11.0-dev.926+266e2e9a3).

mach: fix compiler error about missing field_type

---

src/platform/common.zig
src/platform/libmach.zig

Workaround originally added in #548. Fortunately, the upstream issue has since been resolved. I removed the check
enforcing more than zero fields in `App`, but kept the check ensuring that `App` is a struct.
Upstream issue here: https://github.com/ziglang/zig/issues/12275

mach: remove compiler error for missing field in app (upstream issue fixed)

---

libs/glfw/src/Window.zig
src/platform/native.zig
src/structs.zig

Fixes #620 and Fixes #581 and Fixes #527 and Helps #534
looks like transparent windows aren't supported by dawn. it's also a hint that must be set before window creation

glfw: accept null cursor in Window.setCursor

---

build.zig
dev/template/README.md
libs/basisu/build.zig
libs/earcut/README.md
libs/earcut/build.zig
libs/ecs/build.zig
libs/freetype/README.md
libs/freetype/build.zig
libs/gamemode/build.zig
libs/glfw/README.md
libs/glfw/build.zig
libs/gpu-dawn/sdk.zig
libs/gpu/sdk.zig
libs/model3d/build.zig
libs/sysaudio/sdk.zig
libs/sysjs/build.zig
tools/wasmserve/wasmserve.zig

Prior to this commit, the build system heavily assumed that the result of `@src.file` would always be absolute, but this is no longer guaranteed, likely due to there being no such thing as an "absolute path" in WASI.
It appears that for normal invocations of `zig build`, it is safe to assume that `@src.file` is absolute. However, when ZLS uses a custom `build_runner.zig` to collect build configuration, `@src.file` is actually relative to the current working directory, at least on my system. For a while, this led to ZLS completions breaking entirely, but presently it actually causes ZLS to crash!
The solution is not as simple as using relative `sdkPath` results as-is, because the build system may attempt to resolve these paths relative to build root, when the paths are actually relative to …

all: build: fix sdkPath for relative @src.file / fix autocompletion with ZLS / IDEs

---

libs/glfw/README.md
libs/glfw/src/Cursor.zig
libs/glfw/src/Joystick.zig
libs/glfw/src/Monitor.zig
libs/glfw/src/Window.zig
libs/glfw/src/clipboard.zig
libs/glfw/src/errors.zig
libs/glfw/src/key.zig
libs/glfw/src/main.zig
libs/glfw/src/native.zig
libs/glfw/src/opengl.zig
libs/glfw/src/time.zig
libs/glfw/src/vulkan.zig
src/platform/native.zig

When I wrote mach-glfw (one of my earliest Zig projects, in fact) - the hope was that we could map GLFW errors to nice Zig errors. This is not a new approach to me, in fact years ago I was one of the original authors of the best GLFW bindings in Go where we used a similar approach, and encouraged GLFW to more clearly document errors it can return etc.
The problem is that GLFW still today is very much not designed/intended to be used in a way where errors are handled per-function-call. The general expectation is that you will check errors at important points, or via a callback. 
* GLFW documentation of what errors specific functions can generate is not always 100% correct, and often errors can be rather vague (e.g. `GLFW_PLATFORM_ERROR`)
* Even when a function is documented as possibly …

glfw: complete overhaul of error handling (remove Zig errors)

---

build.zig
dev/template/README.md
libs/basisu/build.zig
libs/earcut/README.md
libs/earcut/build.zig
libs/ecs/build.zig
libs/freetype/README.md
libs/freetype/build.zig
libs/gamemode/build.zig
libs/glfw/README.md
libs/glfw/build.zig
libs/gpu-dawn/sdk.zig
libs/gpu/sdk.zig
libs/model3d/build.zig
libs/sysaudio/sdk.zig
libs/sysjs/build.zig
tools/wasmserve/wasmserve.zig

This reverts commit a1fe671db8fcea21a99a98448acf3b3ceea31fe9.
Lue suggested reverting #661 because ZLS worked around the issue of @src being relative in that environment: https://github.com/zigtools/zls/pull/898
This is not a perfect solution (what zls did seems to be a workaround), but is good enough for us until Zig gets an official package manager.

Revert "all: build: fix sdkPath for relative @src.file / fix autocompletion with ZLS / IDEs (#661)"

---

libs/glfw/README.md
libs/glfw/src/Cursor.zig
libs/glfw/src/Joystick.zig
libs/glfw/src/Monitor.zig
libs/glfw/src/Window.zig
libs/glfw/src/clipboard.zig
libs/glfw/src/errors.zig
libs/glfw/src/key.zig
libs/glfw/src/main.zig
libs/glfw/src/native.zig
libs/glfw/src/opengl.zig
libs/glfw/src/time.zig
libs/glfw/src/vulkan.zig
src/platform/native.zig

`getError()` now returns a struct `Error` containing `error_code` and `description`. Rationale: retrieving the error code with the previous implementation of `getError()` caused `getErrorString()` to return null (the reverse is also true), so it was difficult to obtain both values at the same time. The new implementation allows both values to be retrieved at once.
The previous `getError()` function has been renamed to `getErrorCode()` to reflect the fact that it returns a simple Zig error rather than the `Error` struct. The error set returned by `getErrorCode()` is now named `ErrorCode` rather than `Error`.
The behavior of the `getError()` family of functions clearing the stored error is unchanged. However, since all code that used `defer glfw.getError() catch {}` to explicitly clear …

glfw: refactor `getError` and related functions

---

libs/gpu/build.zig
libs/gpu/examples/sample_utils.zig

I noticed the triangle example in `libs/gpu` stopped working (ran with `zig build run-example`).
It looks like https://github.com/hexops/mach/commit/a52c6e5f5c92ae0f83f919dd6fd088db0dce34db accidentally removed glfw from `libs/gpu/build.zig` and `libs/gpu/sdk.zig`. I could be missing something, but re-adding the dependency got the `libs/gpu` example building again.
One other issue was the change to Dawn that requires the next chain to be null needed handled. I blindly copied the change discussed here:  https://github.com/hexops/mach/pull/672#pullrequestreview-1248810820

gpu: add glfw dependency to example and fix issue

---

shaderexp/main.zig
src/Core.zig
src/engine.zig
src/platform/libmach.zig
src/platform/native/Core.zig
src/platform/wasm/Core.zig

Prior to this change `mach.Core.init` would heap allocate the structure, returning `*Core`:
```zig
app.core = try mach.Core.init(allocator, .{});
```
This was obviously not ideal, but wasn't possible to eliminate before due to how Core was entangled with the platform abstraction. Now that it has been removed, we can reduce Core initialization to take a `*Core` to initialize. In practice this means initialization looks something like this:
```zig
try mach.Core.init(&app.core, alloctor, .{});
```
Or more simply:
```zig
try app.core.init(allocator, .{});
```
And we eliminate the `*Core` allocation entirely in most cases.

mach: eliminate heap allocation of Core

---

libs/core/src/Core.zig
libs/core/src/platform.zig
libs/core/src/platform/native/Core.zig
libs/core/src/platform/wasm/Core.zig
shaderexp/main.zig

After this change:
* `Core.pollEvents` returns an iterator. At the time of polling events, Mach core will perform work to poll for events, handle resizing of the framebuffer, etc. and the iterator allows the caller to consume all available events.
* The event queue is now baced by a `std.fifo.LinearFifo`, which removes the need for dynamic allocation of each event. Instead, the event queue starts with a generous size suitable for most high-end gaming setups (high-precision mouse, etc.) and can grow, but never shrink, up to the maximum event queue size experienced by the app within any given frame. Effectively, this means we find the maximum capacity needed to store events and avoid runtime allocations.
* `Core.hasEvent` is removed.
Notably, since event polling on Desktop platforms is now …

core: make Core.pollEvents return an iterator; remove Core.hasEvent

---

libs/gpu-dawn/sdk.zig

A simple rename of a function from the standard library.

gpu-dawn: update gzip decompression to use latest stdlib API

---

libs/gpu-dawn/sdk.zig

Previously, when the gpu-dawn SDK attempted to fetch Dawn sources, Git failed with this error:
```
fatal: ambiguous argument 'generated-*': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```
This caused the whole build to fail as the gpu-dawn SDK is unable to check out the intended revision of the generated Dawn sources. This commit fixes the issue by using `git checkout --force` instead of `git reset --hard`, which works because you can checkout to a detached commit hash (used by DirectXShaderCompiler, for example) as well as an actual branch.
The alternative would be to do `git reset --hard origin/generated-*` rather than `git reset --hard generated-*`, but that would require …

gpu-dawn: fix git error when fetching Dawn source

---

libs/glfw/src/vulkan.zig

I know this is a very trivial PR but I thought I may as well just fix it when I saw it :) I'm not sure why it wasn't picked up by the "syntax" test in the file tho...

glfw: Fixed type error in vulkan.createWindowSurface

---

libs/core/src/platform/native/entry.zig
libs/core/src/platform/wasm/entry.zig

This commit fixes exporting of the logging std lib options, which was not updated for the `std_options` change.

core: fix usage of std_options for log_level and log_scope_levels

---

libs/freetype/src/Face.zig
libs/freetype/src/Library.zig
libs/freetype/src/freetype.zig
libs/freetype/src/harfbuzz/common.zig
libs/freetype/src/harfbuzz/font.zig
libs/freetype/src/harfbuzz/shape.zig
libs/freetype/src/harfbuzz/shape_plan.zig
libs/freetype/src/main.zig

This fixes some ill-defined string types in Freetype and Harfbuzz.
For example, `createFace` previously accepted non zero-terminated font paths, which would cause a runtime error.
I've checked all usages of type `[]const u8` in Freetype and Harbuzz.
After this PR, all type bugs related to zero-terminated strings should be fixed.
The Harfbuzz `Shapers` type is a bit tricky. Some references:
- [`hb_shape_full` rendered doc](https://harfbuzz.github.io/harfbuzz-hb-shape.html#hb-shape-full), see `shaper_list`
- [`hb_shape_full` src](https://github.com/harfbuzz/harfbuzz/blob/04a47932a3844f7e73e3af8b05fb98c8b54fb779/src/hb-shape.cc#L125)
- [Definition of a `Shapers` list](https://github.com/harfbuzz/harfbuzz/blob/04a47932a3844f7e73e3af8b05fb98c8b54fb779/src/hb-shape.cc#L55)

freetype, harfbuzz: Fix string-related types

---

libs/dusk/src/Parser.zig
libs/sysaudio/src/pipewire.zig

This PR resolves #771 by removing Zig's stdlib `std.math.min()`/`.max()` functions and replacing them with the `@min()`/`@max()` compiler builtin functions.
Please note that this PR will move from being a draft to RFR status once the other repositories have been effectively updated, therefore making this part of the issue tracker.

mach: update to @min/@max (std.math.min/max is going away)

---

src/gfx/util.zig

Update to the @memset builtin fixes the cubemap and pbr-basic examples assuming zigimg is also up to date
mem.set() appears to have been deprecated
This change gets the cubemap and pbr-basic demos running again with zig11-dev
The zigimg dependency also calls the mem.set() function, and it looks like they have already updated on their end, but I'm not experienced enough with the codebase or github to know how that would get pulled in
This is my first pull request so I'm not sure if I'm following all the correct procedures here
Let me know if any additional changes are necessary :)

mach: fix deprecated mem.set() call

---

libs/gpu-dawn/sdk.zig
libs/gpu/src/dawn_impl.zig
libs/gpu/src/interface.zig
libs/gpu/src/queue.zig

This is a WIP PR to update us to the latest Zig version.
Nightly Zig has some large regressions right now in peer type resolution behavior; so we cannot upgrade yet. Once https://github.com/ziglang/zig/pull/15726 lands, we probably can.
```
shaderexp/main.zig:150:22: error: expected type '[]*const command_buffer.CommandBuffer', found '*const [1]*command_buffer.CommandBuffer'
app.queue.submit(&[_]*gpu.CommandBuffer{command});
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
shaderexp/main.zig:150:22: note: cast discards const qualifier
libs/gpu/src/queue.zig:58:51: note: parameter type declared here
pub inline fn submit(queue: *Queue, commands: []*const CommandBuffer) void {
^~~~~~~~~~~~~~~~~~~~~~
```

update to latest Zig version

---

app/Builder.zig
app/main.zig
libs/core/src/platform.zig
libs/gpu/src/main.zig

beginning work on https://github.com/hexops/mach/issues/796, wasnt sure how to handle `callbacks.zig` and `types.zig` since they have so many more decls than the others so just left as is for now.
just merged was slightly new usage of `std.mem.split` https://github.com/ziglang/zig/pull/15579. The old `split` function still works but is just an alias for `splitSequence` and is being deprecated.

core/gpu: start on usingnamespace issue and new zig split usage

---

libs/freetype/build.zig

This wasn't actually broken due to a Zig bug, but rather due to some pragmas in Harfbuzz which forcibly enable this -Werror. Luckily, there's a macro you can define to disable them.

freetype: fix and re-enable harfbuzz

---

libs/gpu-dawn/README.md
libs/gpu-dawn/sdk.zig
libs/gpu/README.md

Supersedes https://github.com/hexops/mach/pull/703 and updates us to the latest Dawn version / API `generated-2023-06-18.1687119009`. This [include ~800 commits](https://github.com/hexops/dawn/compare/9b071ba3cf12eaed09616bc1dd1307b158a94814...1a6339511862c55761652038310f80b31fdd824f) since we last updated (2023-01-28).
Confirmed working on aarch64-macos, should work on others but will need to verify + potentially fix minor `sdk.zig` issues for other platforms.
A second PR will be sent for the `mach-gpu` interface changes that are needed once this is building in CI.
Once merged, Wrench should keep us up-to-date more quickly again - every two weeks or so.

gpu-dawn: begin building latest Dawn version again

---

libs/core/src/Core.zig
libs/core/src/platform/native/Core.zig

core: add is_headless to specify hidden window before init

---

libs/glfw/src/Joystick.zig
libs/glfw/src/Monitor.zig
libs/glfw/src/Window.zig
libs/glfw/src/vulkan.zig

Fixed uses of alignCast where zig fmt was unable to.

glfw: Fixed all uses of the alignCast builtin

---

src/engine.zig
src/gfx2d/Sprite2D.zig
src/gfx2d/shader.wgsl

This is a complete redesign of Sprite2D, the low-level ECS module for sprite rendering.
* Sprites can now use custom shaders (and you can specify a shader per batch.)
* You are no longer limited to one global texture; different sprite batches can have different textures.
* Multi-texturing support (4 max)
* A clear path to multiple render-pass support, should you ever want it.
* The `Engine` module now manages render passes and frame submission; which means Sprite2D can now be used with other ECS modules that render onto the screen too.
On a Macbook M1, with sprites that are independently CPU animated each frame (single texture/shader), we see gains of +60% in release builds:
| Optimization | Frame rate | Before         | After         | Performance | Note            | …

gfx2d: complete redesign of Sprite2D

---

src/math/quat.zig
src/math/vec.zig

Initial Quaternion implementation.

math: add initial Quaternion implementation

---

src/math/vec.zig

---
Rewrote the old commented out tests in accordance to the Mach style guide and added the listed missing basic tests.
While doing so I also caught two bugs in the cross and swizzling methods:
- the naming of the Vec3 swizzling method was wrong, using `yzw` instead of `yzx`, and `.w()` instead of `.x()`, while cross was calling `yzx`
- the cross method used e.g. `.mul(b.xzy())` instead of `.mul(&b.xzy())`

math: Rewrite Vec tests and fix Vec cross calculation bug

---

src/math/vec.zig

---
Motivated by the previously associated TODO note.
This strategy allows for generalized arbitrary swizzling instead by using an enum and the builtin [\@shuffle](https://ziglang.org/documentation/master/#shuffle) function.
- old: `a.yzx()`
- new: `a.swizzle(.y, .z, .x)`

math: Implement new Vec swizzle method

---

src/math/mat.zig

Added function to multiply a matrix with a vector (Matrix* Vec).

Added mulVec function for matrices

---

src/math/main.zig
src/math/ray.zig
src/testing.zig

-----
Implementation of a `Ray` type and a ray-triangle intersection check function in 3D space. 
```
pub fn triangleIntersect(
ray: *const Ray,
va: *const math.Vec3,
vb: *const math.Vec3,
vc: *const math.Vec3,
backface_culling: bool,
) ?RayHit
```
My implementation is based on [Woop et al.](https://www.jcgt.org/published/0002/01/05/). Supports backface culling, since previous hits are not a parameter it is only used to consider a collision on triangle backface a miss if activated.
On hit this will return a `RayHit` which contains the hit distance and hit barycentric coordinates. The return type is optional and it will simply return early on a miss.
Basic tests are included, but could and should be expanded with more tricky examples afterwards.
If accepted this resolves #876.

math: Ray-triangle intersection

---

src/math/mat.zig
src/math/vec.zig

Add function to allow a matrix to be left multiplied by a vector. Not quite sure about the naming of the multiplication functions. Would be happy to hear any suggestions if needed.

Add mulVec function for vectors

---

src/math/ray.zig

-------
Added some more precise test cases for the ray-triangle intersection function.
I created these test cases the following way:
- Generate a random 3D triangle
- Sample a random point on/inside the triangle
- Calculate the barycentric coordinates of the sampled point
- Create a random ray origin point
- Calculate the normalized direction vector
- Calculate distance
(Did the calculations in Mathematica)
------
This PR also fixes a bug with the Ray type so that the `Rayd` and `Rayh` types work properly now and cleaned up the code a bit in the process: e.g. removed the `floatFallbackPrecision` function and replaced it with a simple switch expression. `Ray.Hit` is also now properly generic based on the specific `Ray` type, and will be either a `math.Vec4`, `math.Vec4d` or `math.Vec4h` …

math: More precise triangleIntersect tests and Ray type improvements/bugfixes

---

src/engine.zig

Noticed a memory leak with the basic triangle example. An encoder release was forgotten.

engine: release encoder properly

---

src/math/mat.zig

--------
Motivated by the associated `TODO` comment.
Tests for Matrix multiplication with `Mat4x4` and `Mat3x3`. Caught a bug which causes the `Mat3x3` test to fail. The reason being that `Mat3x3` uses `Vec4`s, I assume this is for padding and compatibility reasons.
The culprit can be found in this line of the `mul` implementation:
```zig
var result: Matrix = undefined;
```
This does not matter for `Mat4x4` since every row and column gets touched. But for when creating a `Mat3x3` we call `init` with a `Vec3` but the `init` method sets the last column of the internal `Vec4` to `1`, so if the values start `undefined` it makes testing against and comparison with an expected `Mat3x3` fail.
Example:
```
============ expected this output: =============  len: 3 (0x3)
[0]: math.vec.Vec(4,f32){ .v …
```

math: Add Matrix multiplication tests

---

src/math/main.zig
src/math/mat.zig
src/math/vec.zig

-----
Turns out 3 element vectors already give us the alignment we want. This change fixes `Mat3x3` comparison while still allowing the `gpu_compatibility` tests to pass without modification.

math: Make Mat3x3's underlying type Vec3

---

src/math/vec.zig
src/testing.zig

----
Once accepted (and finished), helps #1109
Based on the testing implementation, which I left untouched for now. Naming based on the old [Matrix equality functions](https://github.com/hexops/mach/blob/260802f7771c651246930455dfd7de7a75c9869a/src/math/mat.zig#L354).
Let me know if this follows the intended direction.

math: Add vector comparison functions

---

src/core/main.zig
src/core/platform/glfw/Core.zig
src/core/platform/wayland/Core.zig
src/core/platform/x11/Core.zig

Added field swap_chain_usage to core.Options, as well as replacing the default usage flags with this in glfw, x11, and wayland platform

added swap chain usage flags to core.init() options

---

src/sysgpu/shader/ErrorList.zig

It was erroring due to an unnecessary trailing semicolon that dawn was fine with, and the error location was 0 bytes long so it overflowed
```
null:45:1 error: expected global declaration, found 'EOF'
45 │ 
^
```
```wgsl
struct VertexInput{
…
}; // <- extra semicolon at the end of the file caused an error. earlier extra semicolons were fine.
```

sysgpu: fix overflow trying to report an error

---

src/math/ray.zig

The `maxDim` function could be further optimized to remove an unnecessary check. The removed check used to observe whether `v[2]` was already greater than `v[0]`, but this is already known because in order for the function to reach that point `v[1]` has to be greater than or equal to `v[0]` and `v[1]` has to not be greater than `v[2]`, so the greatest dimension must be `v[2]` at that point. The removal of this check also removes the need for the final `return 0;` because the else case covers the case in which all three are the same length. This should result in a small performance gain.
The function is still a bit hard to read, which is probably how the unnecessary check snuck in.

math: simplify algorithm finding greatest dimension vector

---

examples/core-custom-entrypoint/App.zig
examples/custom-renderer/App.zig
examples/custom-renderer/Renderer.zig
examples/glyphs/App.zig
examples/glyphs/Glyphs.zig
examples/piano/App.zig
examples/play-opus/App.zig
examples/sprite/App.zig
examples/text/App.zig
src/Audio.zig
src/Core.zig
src/core/main.zig
src/gfx/Sprite.zig
src/gfx/SpritePipeline.zig
src/gfx/Text.zig
src/gfx/TextPipeline.zig
src/main.zig
src/module/entities.zig
src/module/main.zig
src/module/module.zig

Previously our module system / ECS had two concepts of executable code ('systems' in other ECS), 'local events' and 'global events':
* Local events were where one module would schedule a function to run on another specific module.
* Global events were where one module would say 'an event has occurred' and any other module (potentially multiple) could react to it by having their function get scheduled for execution.
Global events were intended to be _unordered execution_, a point of parallelism opportunity to run multiple functions at once across different threads.
However, in practice, we don't have this multi-threaded capability yet - and it was easy to accidentally end up observing execution order of global events' handler functions. There is also some suspicion that it is not the right …

module: remove global events, rename events -> systems, hinder/remove 'event arguments'

---

src/sysaudio/wasapi.zig

This fixes a crash in the `play-opus` example on my Windows 11 machine, wherein no audio format is selected and crashes when trying to read from `device.formats[0]`.
(Stacktrace for reference: https://gist.github.com/Andoryuuta/defa7bef64bfd5d14e913e5dd9b04284)
Additionally, while debugging this, I found that the example would also crash on startup when my microphone was not plugged in. Small drive-by fix for that is included in this MR as well.
This "works on my machine", but I'm not confident I understand the intentions of the previous code enough to say that this is completely correct.

sysaudio: fix wasapi format selection + fix crash without capture device

---

src/core/platform/glfw/Core.zig
src/core/platform/x11/Core.zig

Note: I fixed the logic in the x11 backend too even though it appears showing/hiding the window is still unimplemented

Headless fix

---

build.zig
build.zig.zon
src/Core.zig
src/core/darwin.zig
src/main.zig
src/sysgpu/metal.zig

Initial macOS backend to replace GLFW. Still heavily experimental, no input, etc. but it renders a triangle at least. Special thanks to mjbshaw for contributing a bulk of this through various PRs.
Next up will be to alter/refactor the `mach.Core` API in some pretty substantial ways.

initial macOS backend

---

src/Core.zig
src/core/win32.zig
src/core/win32/win32.zig
src/gfx/Sprite.zig
src/sysgpu/d3d12.zig
src/sysgpu/shader/codegen/hlsl.zig

Rebased version of https://github.com/hexops/mach/pull/1241

core: win32: various improvements

---

src/sysgpu/main.zig

The sysgpu backend build option was treating the build option as the wrong enum type. This type is defined in `build.zig` and is exposed through the generated `build_options` struct. This is really nasty, but I think this is the correct way to do this. 
The generated code for `@import("build_options")` for reference:
```
pub const want_mach: bool = true;
pub const want_core: bool = true;
pub const want_sysaudio: bool = true;
pub const want_sysgpu: bool = true;
pub const @"build.SysgpuBackend" = enum (u3) {
default = 0,
webgpu = 1,
d3d12 = 2,
metal = 3,
vulkan = 4,
opengl = 5,
};
pub const sysgpu_backend: @"build.SysgpuBackend" = .opengl;
pub const @"build.Platform" = enum (u3) {
wasm = 0,
linux = 1,
windows = 2,
darwin = 3,
null = 4,
};
pub const core_platform: @"build.Platform" = .linux; …
```

Fix sysgpu_backend build option 

---

src/core/Linux.zig
src/core/linux/Wayland.zig
src/core/linux/X11.zig

Utilized previous Wayland implementation as a base, but made the following changes:
- used separate structs for `Linux` and `Wayland`/`X11`, then placed properties in more-or-less the correct place. e.g. properties that belong to Wayland are in `Wayland.zig`. Properties that belong to any Linux implementation belong in `Linux.zig`. I did not do this perfectly, but it can be iterated on later (especially after X11 is implemented).
- plugged `Wayland` into the new event loop
- namespaced all of the listener code (`registry_listener` for example) because all the listeners consist of one or more functions, and an actual listener with is an instance of a struct that holds pointers to those functions. The functions aren't used anywhere else, so it made sense to me to package the listener struct …

core: reimplement Wayland support

---

src/sysgpu/vulkan.zig

I have verified that none of the type casting will be performed on values that are out of range of the destination. The values are all known at compile time and are very low (less than 10).

all: linux support for Zig 2024.10.0-mach

---

src/core/Linux.zig
src/core/linux/Wayland.zig
src/core/linux/X11.zig

This PR makes the following changes:
- enable x11
- use `MACH_BACKEND` env var instead of `MACH_CORE_BACKEND` for selecting linux display server
- fix minor window size discrepancy bug in wayland
- add logging for both x11 and wayland that explain that not all features are supported yet

core: enable x11, employ `MACH_BACKEND` env var, minor fixes/tweaks

---

src/Core.zig
src/core/Linux.zig
src/core/linux/X11.zig

Fixes: https://github.com/hexops/mach/issues/1288
Related to:
https://github.com/hexops/mach/issues/1232
https://github.com/hexops/mach/issues/1252 
https://github.com/hexops/mach/issues/1253
https://github.com/hexops/mach/issues/1259
https://github.com/hexops/mach/issues/1270
https://github.com/hexops/mach/issues/1271
https://github.com/hexops/mach/issues/1275
1. add: deviceTick call after platform update.
2. add: display name to `error.FailedToConnectToDisplay` message.
3. fix: double free during X11 deinit.

Call sysgpu device tick

---

src/core/Linux.zig
src/core/linux/Wayland.zig

As discussed in https://github.com/hexops/mach/issues/1275, this PR is a stopgap until we implement Client Side Decoration in Mach.
If the decoration interface is not found, an error is returned so that the system can attempt a fallback to x11.

Wayland should error when no server side decoration

---

src/Core.zig
src/core/linux/X11.zig

Closes https://github.com/hexops/mach/issues/1290
yppy provided some excellent advise on discord:
> XInitThreads should be the first xlib function called (though im not sure i would believe in xlib multithreading...)
And after I mentioned an error code on exit, they also advised:
> error 3 is badwindow
> probably something is using it after XDestroyWindow
The discussion after lead to the realization that `platform.deinit` is called *before* the GPU backend is released. This caused a race condition where the GPU backend might interact with the window before it is released.
* change: `libx11.XInitThreads` is now called first when initializing X11.
* remove: X11's custom `errorHandler` in favor of the default handler's more verbose description.
* change: `platform.deinit` is now called …

Call XInitThreads first; XCloseDisplay cleanup

---

build.zig.zon
src/core/Darwin.zig

…`windowWillResize:toSize` callback.
I also reworked the `init` code to center the created window, as well as use `options.size` to create the window rather than using arbitrary size.
This PR will need to stay open until [this PR](https://github.com/hexops/mach-objc/pull/25) is merged so we can update the `build.zig.zon` to reference the new `mach-objc` commit.

core: darwin: Implement `update`, `setTitle` and `setSize`, etc.

---

src/core/linux/Wayland.zig

This should get CI back green.

wayland: Remove references to `wl.state`

---

src/module.zig

As you mentioned in the previously merged PR

obj: Make field tracking use a single bitset

---

examples/core-custom-entrypoint/App.zig
examples/core-triangle/App.zig
src/Core.zig
src/core/Darwin.zig
src/core/Null.zig
src/core/Windows.zig
src/module.zig

This PR is stacked on top of #1308, so review that one first.
At the moment, this PR breaks a lot and only triangle example on macOS is building. The effort here is to move more of Core to use the object system, first of these efforts is to treat windows as a list of objects so all window-dependent fields have been moved to `core.windows` and `Platform.tick` just checks for field changes and responds accordingly.

obj: Move `Platform` and `InitOptions` fields into `core.windows`

---

src/Core.zig
src/core/Windows.zig

windows: implement `tick`, call `core.initWindow`, various fixes

---

build.zig
examples/core-triangle/App.zig
examples/play-opus/App.zig
src/Audio.zig
src/core/Darwin.zig
src/graph.zig
src/main.zig
src/module.zig

* various bug fixes to the object system
* various bug fixes for `mach.Core` darwin backend
* rewrote `mach.Audio` to use the new object system
* `examples/play-opus` now working again

various object system fixes; Audio module and play-opus working

---

build.zig.zon
examples/core-transparent-window/App.zig
src/Core.zig
src/core/Darwin.zig
src/core/Windows.zig

Requires [this](https://github.com/hexops/mach-objc/pull/31) mach-objc PR to be merged before we can update the zon for this one.

core: platform: Input callbacks, corrected framebuffer/window sizes, swapchain handling

---

src/core/Linux.zig
src/core/linux/Wayland.zig
src/core/linux/X11.zig

* Setup Wayland to use new mach object system
* In listeners, such as `wl_registry_add_listener`, rather than sharing a pointer to an instance of `Linux` with the Wayland server, pass the mach object system window id.
* Store a pointer to `Core` in the global scope of `Wayland` so that listeners can use the provided window id and pointer to `Core` to lookup the data for that window, modify it, and save it directly in the handler function. See `registryHandleGlobal()` [definition](https://github.com/hexops/mach/pull/1319/files#diff-1275ab21c249f178087e859f98791a64c2b4aedc3c0c4ac7686da18b258b529dL329) for an example.
* Handle some errors that were previously unhandled
* Handle getting and setting the state of windows when needed. Previously a step that wasn't done because we only had 1 …

linux: setup with new object system

---

src/module.zig

This provides a fix for when re-adding items dropped on the floor. Items which are already in the recycle bin are no longer added a second time.

Fix for Object Recycling

---

src/core/linux/Wayland.zig
src/core/linux/X11.zig
src/gamemode.zig
src/main.zig
src/sysaudio/alsa.zig
src/sysaudio/jack.zig
src/sysaudio/pipewire.zig
src/sysaudio/pulseaudio.zig
src/sysgpu/opengl/proc.zig
src/sysgpu/vulkan.zig

Potential fix for #1327
TL;DR This instruments the calls to `DynLib.open` to log exactly what libraries are missing and returns a consistent `LibraryNotFound` error.
---
As for the issue I was running into earlier: The open call in `src/sysgpu/vulkan.zig` was not catching and returning in the same manner as the other library loads, which is why I was getting that non-descript `FileNotFound` error.
One caveat is that some libraries that aren't _really_ required will still log an error, but it's definitely better than the ambiguous errors from before imo.
There may be a better name and/or a better place to put the `loadLibrary` function, so I'm open to shifting some things around if y'all see fit. Cheers!
---

all: instrument library loading

---

src/module.zig

found a ~10% speedup in the sprites example. the `get` and `set` methods on `MultiArrayList` should probably be avoided more often than not as it requires accessing each field which somewhat defeats the purpose

use multiarraylist more optimally in mach.Objects

---

src/math/vec.zig

These seem like useful functions that I could use. Imagine my surprise when they didn't work! This PR should fix that.

Fix Shared VecN comparison operators
